2019-07-03 11:53:46,825 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AA58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/af14abf61d4a55be51c56cf17410b734
2019-07-03 11:53:47,841 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/af14abf61d4a55be51c56cf17410b734
2019-07-03 11:53:48,857 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169389B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/af14abf61d4a55be51c56cf17410b734
2019-07-03 11:56:04,257 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 11:57:28,563 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 11:58:36,784 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 11:58:46,824 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 11:59:05,109 - INFO - register_de.py[:223] - SullyaMelic910@anker.wiki用户注册成功！
2019-07-03 11:59:07,043 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 11:59:10,237 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1216d089b45adfdff949e0ac3bfd9d93
2019-07-03 11:59:11,240 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BD7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1216d089b45adfdff949e0ac3bfd9d93
2019-07-03 11:59:12,243 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C53828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1216d089b45adfdff949e0ac3bfd9d93
2019-07-03 12:00:41,165 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:02:00,658 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:03:21,928 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:09:22,819 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 12:10:38,542 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:12:24,635 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 12:13:20,817 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 12:13:30,850 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 12:14:01,263 - INFO - register_de.py[:223] - CharityaDeidraa045@shein.kim用户注册成功！
2019-07-03 12:14:05,709 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 12:14:09,881 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AFD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2a5435f94ac4caa58b0b402c210ea54f
2019-07-03 12:14:10,907 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2a5435f94ac4caa58b0b402c210ea54f
2019-07-03 12:14:11,910 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2a5435f94ac4caa58b0b402c210ea54f
2019-07-03 12:17:52,030 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 12:19:19,158 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:20:33,874 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:22:46,223 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 12:28:39,500 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 12:29:57,556 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 12:31:57,403 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 12:32:07,441 - INFO - register_de.py[:100] - 个人信息设置失败！failed,Quit!
2019-07-03 12:33:28,206 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:34:59,782 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:36:12,724 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:37:23,135 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:38:38,191 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 12:40:44,393 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 12:42:21,449 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 12:42:26,836 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 12:54:33,769 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 12:58:53,883 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 12:59:03,921 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 12:59:44,305 - INFO - register_de.py[:223] - FrenchaUrae263@zaful.xyz用户注册成功！
2019-07-03 12:59:45,560 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 12:59:48,755 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/05e7b3fc2be28f346558222feb8bb596
2019-07-03 12:59:49,760 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/05e7b3fc2be28f346558222feb8bb596
2019-07-03 12:59:50,763 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/05e7b3fc2be28f346558222feb8bb596
2019-07-03 13:01:02,012 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:03:16,361 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 13:04:47,406 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 13:05:37,675 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 13:05:47,711 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 13:06:02,835 - INFO - register_de.py[:223] - ZackareaHalleya476@zaful.net.cn用户注册成功！
2019-07-03 13:06:07,850 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 13:06:11,993 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160DAAC8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b984e9841e4bbc32fcd67d21d312833a
2019-07-03 13:06:12,998 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b984e9841e4bbc32fcd67d21d312833a
2019-07-03 13:06:13,996 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160ACF98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b984e9841e4bbc32fcd67d21d312833a
2019-07-03 13:07:31,991 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:10:35,262 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:14:25,434 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 13:17:30,787 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:18:42,079 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:21:19,875 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 13:23:38,613 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 13:23:48,766 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 13:24:29,368 - INFO - register_de.py[:223] - RubyeTamikae824@zaful.fun用户注册成功！
2019-07-03 13:24:30,104 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 13:24:33,263 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/af4aa96daad35dfd0b9915cbf2ef89b3
2019-07-03 13:24:34,267 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5ACC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/af4aa96daad35dfd0b9915cbf2ef89b3
2019-07-03 13:24:35,275 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/af4aa96daad35dfd0b9915cbf2ef89b3
2019-07-03 13:25:48,776 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:29:10,754 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 13:31:15,797 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 13:31:25,883 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 13:32:06,481 - INFO - register_de.py[:223] - LeanderaSammic572@ninebot.tv用户注册成功！
2019-07-03 13:32:07,972 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 13:32:12,265 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CF978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/99a73391c22ed5d7bafdb87e54cccb0c
2019-07-03 13:32:13,277 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/99a73391c22ed5d7bafdb87e54cccb0c
2019-07-03 13:32:14,278 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F7B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/99a73391c22ed5d7bafdb87e54cccb0c
2019-07-03 13:33:28,520 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:36:16,424 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 13:38:13,619 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 13:39:39,412 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:40:55,211 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:42:19,394 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 13:43:06,117 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 13:43:16,172 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 13:43:36,364 - INFO - register_de.py[:223] - AngeloeKeganc639@ninebot.ltd用户注册成功！
2019-07-03 13:43:40,387 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 13:43:44,561 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/327c07ee9346e8e9f6c6cde7a19a1387
2019-07-03 13:43:45,811 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/327c07ee9346e8e9f6c6cde7a19a1387
2019-07-03 13:43:46,956 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/327c07ee9346e8e9f6c6cde7a19a1387
2019-07-03 13:45:20,279 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:50:31,267 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 13:52:43,879 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 13:55:11,512 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 13:56:52,535 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:02:19,725 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 14:03:29,358 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 14:04:44,695 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:05:54,710 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:08:03,955 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:09:30,980 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:12:34,103 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 14:14:39,886 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:16:39,260 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 14:18:35,626 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 14:20:20,236 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:22:00,513 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 14:23:47,052 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 14:23:57,107 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 14:24:10,781 - INFO - register_de.py[:223] - MiltaRaleighe129@nineboy.top用户注册成功！
2019-07-03 14:24:12,230 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 14:24:16,362 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0eb2c2020322b421335f9e5e3212141a
2019-07-03 14:24:17,371 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0eb2c2020322b421335f9e5e3212141a
2019-07-03 14:24:18,370 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169375F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0eb2c2020322b421335f9e5e3212141a
2019-07-03 14:29:42,225 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 14:31:31,089 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 14:32:35,636 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 14:32:45,671 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 14:33:05,003 - INFO - register_de.py[:223] - AmityaRidgee701@nineboy.pro用户注册成功！
2019-07-03 14:33:07,995 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 14:33:11,126 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160DA940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee1439d0dc4bc39785747d3f49b5efd3
2019-07-03 14:33:12,131 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee1439d0dc4bc39785747d3f49b5efd3
2019-07-03 14:33:13,136 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160DAB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee1439d0dc4bc39785747d3f49b5efd3
2019-07-03 14:34:33,263 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:37:05,492 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 14:38:42,112 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:39:53,600 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:41:22,015 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:46:30,943 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 14:49:01,824 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 14:50:17,599 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 14:51:02,995 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 14:51:13,033 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 14:51:29,996 - INFO - register_de.py[:223] - ChloriscHartmane610@nineboy.site用户注册成功！
2019-07-03 14:51:31,460 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 14:51:34,662 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a6a2d1102e496b127695256e3abeff2a
2019-07-03 14:51:35,666 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169374E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a6a2d1102e496b127695256e3abeff2a
2019-07-03 14:51:36,672 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a6a2d1102e496b127695256e3abeff2a
2019-07-03 14:54:09,588 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 14:55:21,179 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 14:56:43,418 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 14:57:56,191 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 15:00:27,269 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 15:02:40,497 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 15:04:05,042 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 15:04:44,249 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 15:04:54,281 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 15:05:09,933 - INFO - register_de.py[:223] - FissehacBuddye047@nineboy.net用户注册成功！
2019-07-03 15:05:11,141 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 15:05:14,325 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5c6137da1364754e7ae9e0a2c7c1872a
2019-07-03 15:05:15,340 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5c6137da1364754e7ae9e0a2c7c1872a
2019-07-03 15:05:16,342 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5c6137da1364754e7ae9e0a2c7c1872a
2019-07-03 15:07:01,987 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 15:08:42,864 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 15:09:40,146 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 15:09:50,191 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 15:10:07,510 - INFO - register_de.py[:223] - NancDavane034@nineboy.cc用户注册成功！
2019-07-03 15:10:08,558 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 15:10:11,734 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e68bfdba419c9a1975a532f0e680e88
2019-07-03 15:10:12,764 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160C8A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e68bfdba419c9a1975a532f0e680e88
2019-07-03 15:10:13,796 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169385F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e68bfdba419c9a1975a532f0e680e88
2019-07-03 15:11:26,002 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 15:13:02,317 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 15:14:17,506 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 15:16:56,457 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 15:18:19,572 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 15:19:40,114 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 15:21:24,573 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 15:22:47,270 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 15:23:35,505 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 15:23:45,572 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 15:24:00,592 - INFO - register_de.py[:223] - MaracJoshc856@aukey.live用户注册成功！
2019-07-03 15:24:02,241 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 15:24:06,428 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169307F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6c8be382bf96f247070b17eab24b4f89
2019-07-03 15:24:07,433 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716930FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6c8be382bf96f247070b17eab24b4f89
2019-07-03 15:24:08,450 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716930E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6c8be382bf96f247070b17eab24b4f89
2019-07-03 15:25:23,913 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 15:26:46,255 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 15:27:32,122 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 15:27:42,151 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 15:28:00,876 - INFO - register_de.py[:223] - GwendoynaHama053@aukey.fun用户注册成功！
2019-07-03 15:28:02,256 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 15:28:06,394 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4e8d3ef98ac07f4a210e0c77312dbdb6
2019-07-03 15:28:07,404 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4e8d3ef98ac07f4a210e0c77312dbdb6
2019-07-03 15:28:08,421 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4e8d3ef98ac07f4a210e0c77312dbdb6
2019-07-03 15:30:00,821 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 15:33:02,480 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 15:33:12,516 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 15:33:54,751 - INFO - register_de.py[:223] - LanzaeSherwine513@aukey.ltd用户注册成功！
2019-07-03 15:33:56,418 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 15:34:00,758 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169387F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7a4f96c78b72c9f5b0934296efc03879
2019-07-03 15:34:01,772 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7a4f96c78b72c9f5b0934296efc03879
2019-07-03 15:34:02,779 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7a4f96c78b72c9f5b0934296efc03879
2019-07-03 15:36:12,111 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 15:38:34,157 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 15:39:39,104 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 15:39:49,155 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 15:40:19,922 - INFO - register_de.py[:223] - ZakkaryaElliea925@aukey.net.cn用户注册成功！
2019-07-03 15:40:27,286 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 15:40:31,474 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA15C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/213b4ea1921582435428cab3ea2e5f43
2019-07-03 15:40:32,491 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/213b4ea1921582435428cab3ea2e5f43
2019-07-03 15:40:33,510 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/213b4ea1921582435428cab3ea2e5f43
2019-07-03 15:43:49,455 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 15:46:53,657 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-03 15:58:01,080 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 16:03:14,153 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 16:04:34,218 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 16:06:27,392 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 16:08:12,733 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 16:08:22,783 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 16:09:02,965 - INFO - register_de.py[:223] - NuraaDantona067@aukey.mobi用户注册成功！
2019-07-03 16:10:41,318 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d01a7e21bd0d7d49c8076ceaa5632f18
2019-07-03 16:10:42,318 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169305C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d01a7e21bd0d7d49c8076ceaa5632f18
2019-07-03 16:10:43,335 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169300B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d01a7e21bd0d7d49c8076ceaa5632f18
2019-07-03 16:13:06,064 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 16:24:20,964 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 16:25:05,522 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 16:25:15,573 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 16:25:32,573 - INFO - register_de.py[:223] - JubalaPutnama317@nineboys.co用户注册成功！
2019-07-03 16:25:33,630 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 16:25:36,772 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160ACA58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/592aeea97c81f891eae868de1a4339c8
2019-07-03 16:25:37,804 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AE80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/592aeea97c81f891eae868de1a4339c8
2019-07-03 16:25:38,835 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716930C18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/592aeea97c81f891eae868de1a4339c8
2019-07-03 16:26:57,189 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 16:27:42,197 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 16:27:52,243 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 16:28:09,045 - INFO - register_de.py[:223] - LilliaWellaa356@nineboys.store用户注册成功！
2019-07-03 16:28:10,125 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 16:28:14,282 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BD978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c6eb1dd79e596e03225aaa431b1c5316
2019-07-03 16:28:15,314 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716930DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c6eb1dd79e596e03225aaa431b1c5316
2019-07-03 16:28:16,331 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716930278>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c6eb1dd79e596e03225aaa431b1c5316
2019-07-03 16:29:28,402 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 16:30:50,396 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 16:31:38,244 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 16:31:48,292 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 16:32:06,622 - INFO - register_de.py[:223] - RowenacShermanc973@nineboys.art用户注册成功！
2019-07-03 16:32:07,474 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 16:32:10,648 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/306a1c114b3166c074969f17eb3ac7c6
2019-07-03 16:32:11,663 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/306a1c114b3166c074969f17eb3ac7c6
2019-07-03 16:32:12,680 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/306a1c114b3166c074969f17eb3ac7c6
2019-07-03 16:35:41,102 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 16:38:30,310 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 16:39:53,584 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 16:40:38,564 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 16:40:48,596 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 16:41:01,038 - INFO - register_de.py[:223] - ZacharycTermonc186@nineboys.site用户注册成功！
2019-07-03 16:41:02,950 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 16:41:07,095 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5ADA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7973658d6e1703b3146d0ccb14117f9b
2019-07-03 16:41:08,101 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7973658d6e1703b3146d0ccb14117f9b
2019-07-03 16:41:09,102 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7973658d6e1703b3146d0ccb14117f9b
2019-07-03 16:42:53,025 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 16:44:16,291 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 16:44:26,319 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 16:45:06,736 - INFO - register_de.py[:223] - UliciaaMaisiea071@nineboys.pro用户注册成功！
2019-07-03 16:45:08,863 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 16:45:13,026 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4c11fe9ff677fa29e7364bb8982980ae
2019-07-03 16:45:14,047 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169388D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4c11fe9ff677fa29e7364bb8982980ae
2019-07-03 16:45:15,063 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5A710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4c11fe9ff677fa29e7364bb8982980ae
2019-07-03 16:47:23,672 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 16:49:35,203 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 16:52:10,682 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 16:53:53,247 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 16:54:03,287 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 16:54:31,707 - INFO - register_de.py[:223] - HaywardaAnnabalc981@nineboys.org用户注册成功！
2019-07-03 16:54:33,313 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 16:54:36,442 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bed44ac6db67409591f61a5587a6dc20
2019-07-03 16:54:37,454 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716930390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bed44ac6db67409591f61a5587a6dc20
2019-07-03 16:54:38,460 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716930DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bed44ac6db67409591f61a5587a6dc20
2019-07-03 16:55:57,030 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 16:56:45,774 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 16:56:55,797 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 16:57:15,160 - INFO - register_de.py[:223] - CarlosaQuincea783@nineboys.info用户注册成功！
2019-07-03 16:57:16,682 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 16:57:20,029 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4844ef864727f252eba5e82609454d3b
2019-07-03 16:57:21,034 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4844ef864727f252eba5e82609454d3b
2019-07-03 16:57:22,038 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693FF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4844ef864727f252eba5e82609454d3b
2019-07-03 16:59:27,528 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 17:00:52,343 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 17:01:40,500 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 17:01:50,537 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 17:02:24,006 - INFO - register_de.py[:223] - SabrinaeAlizea037@nineboys.top用户注册成功！
2019-07-03 17:02:25,017 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 17:02:28,180 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169377F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/65ec7126307a71ddc0bf8c90baf0284f
2019-07-03 17:02:29,178 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160C8D68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/65ec7126307a71ddc0bf8c90baf0284f
2019-07-03 17:02:30,181 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160C8978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/65ec7126307a71ddc0bf8c90baf0284f
2019-07-03 17:03:55,152 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 17:15:09,099 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 17:15:50,022 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 17:16:00,063 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 17:16:16,642 - INFO - register_de.py[:223] - FrederickcRinge937@nineboys.tech用户注册成功！
2019-07-03 17:16:18,383 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 17:16:22,536 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d8e8835e06b4a545641789cd38e9a0b
2019-07-03 17:16:23,540 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d8e8835e06b4a545641789cd38e9a0b
2019-07-03 17:16:24,543 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d8e8835e06b4a545641789cd38e9a0b
2019-07-03 17:17:42,851 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 17:18:51,999 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 17:19:02,037 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 17:19:24,947 - INFO - register_de.py[:223] - MacbethcGazite216@nineboys.ltd用户注册成功！
2019-07-03 17:19:26,070 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 17:19:29,195 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3141f8c273cd1cba27aafca4a3738c88
2019-07-03 17:19:30,198 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3141f8c273cd1cba27aafca4a3738c88
2019-07-03 17:19:31,205 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169383C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3141f8c273cd1cba27aafca4a3738c88
2019-07-03 17:20:43,868 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 17:21:56,617 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 17:22:35,667 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 17:22:45,701 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 17:23:01,626 - INFO - register_de.py[:223] - SoneEliciac758@nineboys.group用户注册成功！
2019-07-03 17:23:02,758 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 17:23:05,907 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/83f85c11d5bf04a43b6135d9ea0a6964
2019-07-03 17:23:06,909 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693F0B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/83f85c11d5bf04a43b6135d9ea0a6964
2019-07-03 17:23:07,913 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000771693FB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/83f85c11d5bf04a43b6135d9ea0a6964
2019-07-03 17:24:34,472 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 17:25:57,389 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 17:27:17,036 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 17:29:23,490 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 17:30:40,319 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 17:31:22,186 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 17:31:32,228 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 17:31:48,287 - INFO - register_de.py[:223] - ElisacZackarea573@nineboys.xyz用户注册成功！
2019-07-03 17:31:49,337 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 17:31:52,480 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b0a2366df175f1d8481aaf1577c39772
2019-07-03 17:31:53,478 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b0a2366df175f1d8481aaf1577c39772
2019-07-03 17:31:54,483 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b0a2366df175f1d8481aaf1577c39772
2019-07-03 17:33:32,057 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 17:38:54,269 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 17:44:04,198 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 17:45:20,049 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 17:47:06,657 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 17:48:38,156 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 17:54:11,274 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 17:59:29,320 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 18:00:53,443 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 18:01:36,765 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 18:01:46,813 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 18:02:00,981 - INFO - register_de.py[:223] - TyrienneaDebbyc612@nineboy.store用户注册成功！
2019-07-03 18:02:01,838 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 18:02:04,970 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b4729441d4a377b2f645f10c81d7e8a4
2019-07-03 18:02:05,966 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169385F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b4729441d4a377b2f645f10c81d7e8a4
2019-07-03 18:02:06,967 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b4729441d4a377b2f645f10c81d7e8a4
2019-07-03 18:04:01,100 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 18:06:29,233 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 18:07:48,606 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 18:08:35,828 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 18:08:45,889 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 18:08:59,917 - INFO - register_de.py[:223] - BrandeRuperta249@nineboy.group用户注册成功！
2019-07-03 18:09:01,326 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 18:09:04,703 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CF4A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8cbb8206c2e911351dd990341ebba83e
2019-07-03 18:09:05,714 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8cbb8206c2e911351dd990341ebba83e
2019-07-03 18:09:06,723 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169380F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8cbb8206c2e911351dd990341ebba83e
2019-07-03 18:11:34,630 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 18:13:00,324 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 18:13:58,011 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 18:14:08,041 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 18:14:22,912 - INFO - register_de.py[:223] - BridgetteeRodneyc409@nineboy.ltd用户注册成功！
2019-07-03 18:14:26,566 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 18:14:30,913 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CF4E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/407a6129865579d106d224f5a51bcd89
2019-07-03 18:14:31,924 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/407a6129865579d106d224f5a51bcd89
2019-07-03 18:14:32,934 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/407a6129865579d106d224f5a51bcd89
2019-07-03 18:16:32,371 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 18:21:42,398 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 18:23:06,775 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 18:23:53,378 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 18:24:03,419 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 18:24:17,776 - INFO - register_de.py[:223] - DodieaValentinec930@geabest.club用户注册成功！
2019-07-03 18:24:19,309 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 18:24:22,609 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2ba3ea1f5cbd57387f672cbbddb919a6
2019-07-03 18:24:23,611 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2ba3ea1f5cbd57387f672cbbddb919a6
2019-07-03 18:24:24,622 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2ba3ea1f5cbd57387f672cbbddb919a6
2019-07-03 18:30:12,666 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 18:31:30,103 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 18:33:10,666 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 18:35:30,042 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 18:40:39,877 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 18:46:11,706 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 18:47:25,504 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 18:49:18,987 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 18:50:32,006 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 18:52:17,956 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 18:54:41,064 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 18:56:59,899 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 18:57:09,984 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 18:57:52,354 - INFO - register_de.py[:223] - HezekiaheCalc375@geabest.ltd用户注册成功！
2019-07-03 18:57:53,562 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 18:57:57,708 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/606d677ff8481ed26b7c7e98bfbc7132
2019-07-03 18:57:58,741 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/606d677ff8481ed26b7c7e98bfbc7132
2019-07-03 18:57:59,737 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169387F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/606d677ff8481ed26b7c7e98bfbc7132
2019-07-03 19:03:10,718 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 19:04:48,766 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 19:06:03,424 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 19:06:25,475 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 19:17:54,748 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 19:20:03,766 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 19:22:03,501 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 19:28:24,292 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 19:29:57,172 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 19:31:03,157 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 19:33:43,940 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 19:35:36,155 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 19:37:38,731 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 19:41:43,268 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 19:41:53,278 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 19:42:24,656 - INFO - register_de.py[:223] - LauraeDyanic863@geabest.mobi用户注册成功！
2019-07-03 19:42:25,869 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 19:42:30,989 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BD908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7223aa9d0952fa082bd9de07eee3a075
2019-07-03 19:42:32,078 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5ACC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7223aa9d0952fa082bd9de07eee3a075
2019-07-03 19:42:33,145 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDBA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7223aa9d0952fa082bd9de07eee3a075
2019-07-03 19:45:20,340 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 19:47:55,963 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 19:48:06,007 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 19:49:23,363 - INFO - register_de.py[:223] - OlivereKandyc245@geabest.com.cn用户注册成功！
2019-07-03 19:49:27,053 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 19:49:32,566 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e7ca3a2a3cd262ca086a5f5477e4e16
2019-07-03 19:49:33,744 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e7ca3a2a3cd262ca086a5f5477e4e16
2019-07-03 19:49:34,943 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e7ca3a2a3cd262ca086a5f5477e4e16
2019-07-03 19:55:01,996 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 19:56:39,630 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 19:58:16,900 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 20:00:10,331 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 20:01:37,772 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 20:02:58,131 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 20:04:16,683 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 20:06:02,165 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 20:07:16,550 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 20:09:50,395 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 20:12:53,838 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-03 20:28:39,273 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 20:30:09,442 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 20:31:25,514 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 20:33:10,353 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 20:35:02,655 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 20:37:31,238 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 20:37:41,421 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 20:38:26,767 - INFO - register_de.py[:223] - ZavrinaaBudc386@geabest.store用户注册成功！
2019-07-03 20:38:28,044 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 20:38:39,014 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b6338f33e3d541f241772871c9db53e4
2019-07-03 20:38:40,046 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b6338f33e3d541f241772871c9db53e4
2019-07-03 20:38:41,252 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C916D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b6338f33e3d541f241772871c9db53e4
2019-07-03 20:41:07,582 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 20:43:38,343 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 20:49:05,122 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 20:54:18,034 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 20:55:54,093 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 20:57:09,291 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 21:02:25,573 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 21:04:05,857 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 21:05:21,063 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 21:10:31,462 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 21:11:43,434 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 21:14:08,188 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 21:19:25,192 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 21:22:30,891 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 21:25:13,003 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 21:25:23,036 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 21:26:04,803 - INFO - register_de.py[:223] - RaevyneChelsae218@gets.fun用户注册成功！
2019-07-03 21:26:15,101 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 21:26:22,553 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/feaef753cc06db1292b1c485dae66a05
2019-07-03 21:26:23,704 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/feaef753cc06db1292b1c485dae66a05
2019-07-03 21:26:25,053 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169374A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/feaef753cc06db1292b1c485dae66a05
2019-07-03 21:28:01,614 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 21:33:14,092 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 21:34:37,911 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 21:35:49,686 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 21:37:49,713 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 21:43:03,733 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 21:48:16,456 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 21:49:40,990 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 21:51:55,265 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 21:53:06,805 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 21:54:26,613 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 21:55:45,497 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 21:55:56,201 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 21:56:21,381 - INFO - register_de.py[:223] - UlemaaEmanuela796@yyw.link用户注册成功！
2019-07-03 21:56:25,853 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 21:56:31,057 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/114fda119e5a72124755e06693576311
2019-07-03 21:56:32,466 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/114fda119e5a72124755e06693576311
2019-07-03 21:56:33,564 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CF550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/114fda119e5a72124755e06693576311
2019-07-03 21:58:41,970 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 22:00:34,059 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 22:00:44,200 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 22:01:00,303 - INFO - register_de.py[:223] - OsmaneElenorac304@beads.ren用户注册成功！
2019-07-03 22:01:04,932 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 22:01:09,084 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91B38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2e053d76d4390badfea87236d746333a
2019-07-03 22:01:10,087 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937F60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2e053d76d4390badfea87236d746333a
2019-07-03 22:01:11,089 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169376D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2e053d76d4390badfea87236d746333a
2019-07-03 22:02:43,632 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 22:04:07,012 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 22:05:53,313 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 22:09:25,088 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 22:11:28,323 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 22:11:38,370 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 22:11:51,964 - INFO - register_de.py[:223] - YulandaePhylisse456@beads.ink用户注册成功！
2019-07-03 22:11:53,799 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 22:11:57,003 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1b84a135226bab1c134e420b31c0ea83
2019-07-03 22:11:58,014 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160ACF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1b84a135226bab1c134e420b31c0ea83
2019-07-03 22:11:59,025 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C795C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1b84a135226bab1c134e420b31c0ea83
2019-07-03 22:17:28,107 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 22:23:10,737 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 22:24:35,276 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 22:25:55,907 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 22:26:06,538 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 22:26:20,576 - INFO - register_de.py[:223] - MedaaJuditha278@beads.wang用户注册成功！
2019-07-03 22:26:27,754 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 22:26:32,156 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AC18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d5a3b9889da6335ca36c4312c9b0d2b1
2019-07-03 22:26:33,255 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937BA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d5a3b9889da6335ca36c4312c9b0d2b1
2019-07-03 22:26:34,262 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d5a3b9889da6335ca36c4312c9b0d2b1
2019-07-03 22:29:14,708 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 22:31:27,077 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 22:34:35,157 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 22:35:47,885 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 22:41:02,158 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 22:42:38,459 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 22:45:24,386 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 22:47:33,302 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 22:50:23,290 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 22:51:50,741 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 22:54:15,500 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 22:58:21,052 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 23:00:03,844 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 23:02:19,924 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 23:03:58,758 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 23:09:16,738 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 23:15:28,040 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 23:20:43,297 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 23:21:43,434 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 23:27:10,756 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 23:28:52,028 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 23:34:20,110 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 23:39:30,389 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 23:42:32,850 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-03 23:44:49,058 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-03 23:49:57,955 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-03 23:51:35,351 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-03 23:52:27,483 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-03 23:52:37,520 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-03 23:53:01,507 - INFO - register_de.py[:223] - PenleyeSanchoc940@anker.work用户注册成功！
2019-07-03 23:53:04,939 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-03 23:53:09,121 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5ADD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c083596eb3ae69f5d89fc23afcf58274
2019-07-03 23:53:10,118 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c083596eb3ae69f5d89fc23afcf58274
2019-07-03 23:53:11,119 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c083596eb3ae69f5d89fc23afcf58274
2019-07-03 23:59:26,992 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-04 00:00:42,420 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 00:06:31,457 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-04 00:09:35,169 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 00:21:43,251 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 00:24:36,659 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 00:27:23,090 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 00:27:28,350 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 00:39:51,802 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 00:42:06,207 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 00:43:50,609 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 00:45:10,554 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 00:45:29,437 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 00:57:47,202 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 00:59:56,288 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 01:00:06,322 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 01:00:21,668 - INFO - register_de.py[:223] - OmataDottiea398@shein.xin用户注册成功！
2019-07-04 01:00:24,956 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 01:00:29,082 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CF240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/152e5c4beaebccbef8f6be65f16f74fc
2019-07-04 01:00:30,083 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AB70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/152e5c4beaebccbef8f6be65f16f74fc
2019-07-04 01:00:31,080 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AD30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/152e5c4beaebccbef8f6be65f16f74fc
2019-07-04 01:01:40,541 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-04 01:02:55,934 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 01:03:49,986 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 01:04:00,013 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 01:04:17,123 - INFO - register_de.py[:223] - JadencBurkec901@shein.wang用户注册成功！
2019-07-04 01:05:53,253 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CF470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c409fa267b30719cd19ade01db67423a
2019-07-04 01:05:54,275 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c409fa267b30719cd19ade01db67423a
2019-07-04 01:05:55,282 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160ACB70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c409fa267b30719cd19ade01db67423a
2019-07-04 01:08:45,367 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 01:22:01,613 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 01:34:21,952 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 01:35:33,473 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 01:35:43,503 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 01:36:05,326 - INFO - register_de.py[:223] - IldeeFrazera654@shein.kim用户注册成功！
2019-07-04 01:37:34,278 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169378D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8abe07526671c0363ac5f045ea6ae760
2019-07-04 01:37:35,279 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8abe07526671c0363ac5f045ea6ae760
2019-07-04 01:37:36,294 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8abe07526671c0363ac5f045ea6ae760
2019-07-04 01:40:29,210 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 01:53:21,341 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 02:04:58,879 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 02:07:33,370 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 02:07:43,415 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 02:08:24,139 - INFO - register_de.py[:223] - OcrancFrancoisea917@zaful.mobi用户注册成功！
