2019-07-03 13:02:06,945 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 13:03:05,120 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 13:03:15,154 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 13:03:28,959 - INFO - register_us.py[:236] - RonnyaTimothya037@zaful.net.cn用户注册成功！
2019-07-03 13:03:30,854 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 13:03:34,181 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB84A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d924d4d199fbdbd9237f08880ad40345
2019-07-03 13:03:35,176 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d924d4d199fbdbd9237f08880ad40345
2019-07-03 13:03:36,182 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD581D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d924d4d199fbdbd9237f08880ad40345
2019-07-03 13:08:51,254 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 13:14:01,222 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 13:15:12,468 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 13:16:41,840 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 13:17:48,402 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 13:17:58,435 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 13:18:14,066 - INFO - register_us.py[:236] - JamilcWallisc043@zaful.work用户注册成功！
2019-07-03 13:18:15,281 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 13:18:19,421 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/39a65d640549a161e27406b603410c84
2019-07-03 13:18:20,422 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/39a65d640549a161e27406b603410c84
2019-07-03 13:18:21,431 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/39a65d640549a161e27406b603410c84
2019-07-03 13:20:02,154 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 13:21:29,860 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 13:26:54,713 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 13:28:21,474 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 13:29:53,559 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 13:31:40,703 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 13:33:13,681 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 13:38:23,765 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 13:38:28,750 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 13:53:40,724 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 13:55:18,292 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 14:05:44,627 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 14:06:57,024 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 14:12:26,784 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 14:13:52,031 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 14:15:18,542 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 14:16:04,087 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 14:17:13,184 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 14:18:33,804 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 14:19:30,460 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 14:19:39,408 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 14:19:49,446 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 14:20:04,248 - INFO - register_us.py[:236] - MarcaKatae307@nineboy.com.cn用户注册成功！
2019-07-03 14:20:07,226 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 14:20:11,424 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/95683361199e3caacc3ca564981a6fbe
2019-07-03 14:20:12,435 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/95683361199e3caacc3ca564981a6fbe
2019-07-03 14:20:13,452 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/95683361199e3caacc3ca564981a6fbe
2019-07-03 14:25:37,743 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 14:27:04,053 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 14:28:28,302 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 14:33:39,416 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 14:38:49,904 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 14:41:30,331 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 14:42:51,985 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 14:48:19,111 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 14:49:29,360 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 14:51:08,104 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 14:52:20,669 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 14:52:30,705 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 14:52:56,168 - INFO - register_us.py[:236] - PhineaseUisteana683@nineboy.site用户注册成功！
2019-07-03 14:52:58,470 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 14:53:01,669 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/caca548f30b9fc0687b70094edfba798
2019-07-03 14:53:02,688 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CEB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/caca548f30b9fc0687b70094edfba798
2019-07-03 14:53:03,695 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/caca548f30b9fc0687b70094edfba798
2019-07-03 14:54:49,027 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 14:55:52,807 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 14:56:01,451 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 14:56:11,487 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 14:56:25,429 - INFO - register_us.py[:236] - NyleeBeryle890@nineboy.vip用户注册成功！
2019-07-03 14:56:29,408 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 14:56:33,629 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7b1f2d50a5d16c8229b0342f2cbb8bd3
2019-07-03 14:56:34,645 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7b1f2d50a5d16c8229b0342f2cbb8bd3
2019-07-03 14:56:35,676 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9416A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7b1f2d50a5d16c8229b0342f2cbb8bd3
2019-07-03 14:58:12,036 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 14:59:30,440 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 15:00:25,327 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 15:00:33,585 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 15:00:43,625 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 15:01:14,598 - INFO - register_us.py[:236] - KyracPebblese314@nineboy.biz用户注册成功！
2019-07-03 15:01:40,318 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 15:01:44,467 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8cfd096b2a7b2f1aef90eb50071b9ee7
2019-07-03 15:01:45,467 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CF98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8cfd096b2a7b2f1aef90eb50071b9ee7
2019-07-03 15:01:46,467 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8cfd096b2a7b2f1aef90eb50071b9ee7
2019-07-03 15:03:30,536 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 15:05:48,137 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 15:06:56,144 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 15:07:47,992 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 15:07:58,015 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 15:08:10,683 - INFO - register_us.py[:236] - AishaeWindyc854@nineboy.cc用户注册成功！
2019-07-03 15:08:11,644 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 15:08:14,873 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD719E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3dade3c3c7c3d9079d5d2ce2127f782b
2019-07-03 15:08:15,878 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9412E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3dade3c3c7c3d9079d5d2ce2127f782b
2019-07-03 15:08:16,880 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3dade3c3c7c3d9079d5d2ce2127f782b
2019-07-03 15:10:11,826 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 15:11:22,003 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 15:12:13,567 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 15:12:23,586 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 15:12:36,020 - INFO - register_us.py[:236] - OighrigeWindiea813@aukey.online用户注册成功！
2019-07-03 15:12:37,241 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 15:12:40,358 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6f7ab73d0beecb088e6443cdba409a33
2019-07-03 15:12:41,356 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6f7ab73d0beecb088e6443cdba409a33
2019-07-03 15:12:42,361 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6f7ab73d0beecb088e6443cdba409a33
2019-07-03 15:14:17,403 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 15:15:49,096 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 15:18:17,169 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 15:19:26,406 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 15:20:35,197 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 15:22:16,014 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 15:24:36,283 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 15:26:28,342 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 15:26:38,382 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 15:26:52,054 - INFO - register_us.py[:236] - DejahcMatanaa568@aukey.live用户注册成功！
2019-07-03 15:26:56,588 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 15:26:59,764 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/afac8d4af4e189ea45f506f175dd5d46
2019-07-03 15:27:00,766 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90D68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/afac8d4af4e189ea45f506f175dd5d46
2019-07-03 15:27:01,797 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/afac8d4af4e189ea45f506f175dd5d46
2019-07-03 15:28:17,401 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 15:33:27,779 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 15:35:10,356 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 15:36:31,080 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 15:38:03,282 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 15:38:56,591 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 15:39:03,805 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 15:39:13,840 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 15:39:28,035 - INFO - register_us.py[:236] - GonzalocBricee723@aukey.net.cn用户注册成功！
2019-07-03 15:39:39,500 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 15:39:42,670 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/163137dfd9622fbfb79277f7ddde107c
2019-07-03 15:39:43,682 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/163137dfd9622fbfb79277f7ddde107c
2019-07-03 15:39:44,695 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/163137dfd9622fbfb79277f7ddde107c
2019-07-03 15:41:04,167 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 15:42:46,717 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 15:44:47,823 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-03 15:59:57,270 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 16:00:02,691 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 16:12:30,488 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 16:24:08,388 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 16:25:21,701 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 16:25:27,455 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 16:40:34,752 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 16:41:46,452 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 16:43:17,886 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 16:44:33,753 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 16:45:36,872 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 16:45:46,906 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 16:46:14,726 - INFO - register_us.py[:236] - ObadiahcAdea175@nineboys.pro用户注册成功！
2019-07-03 16:46:16,677 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 16:46:20,830 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6d03a69eede2b1d604214ca60c232790
2019-07-03 16:46:21,827 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A2E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6d03a69eede2b1d604214ca60c232790
2019-07-03 16:46:22,836 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6d03a69eede2b1d604214ca60c232790
2019-07-03 16:47:33,828 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 16:49:15,191 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 16:54:25,096 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 16:55:38,328 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 16:56:47,381 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:02:14,973 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:03:06,161 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:08:22,563 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:13:32,310 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:18:40,933 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:23:50,875 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:29:01,435 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:30:27,271 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:35:37,641 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:37:00,387 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:38:54,248 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 17:40:58,340 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 17:43:16,465 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 17:43:26,518 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 17:43:45,339 - INFO - register_us.py[:236] - JerryaMontya641@nineboys.cn用户注册成功！
2019-07-03 17:43:52,930 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 17:43:56,111 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bc35d75686fbe0e6ae4292266750e608
2019-07-03 17:43:57,116 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90DD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bc35d75686fbe0e6ae4292266750e608
2019-07-03 17:43:58,121 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bc35d75686fbe0e6ae4292266750e608
2019-07-03 17:45:09,671 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 17:45:59,201 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 17:46:05,763 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 17:46:15,918 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 17:46:29,346 - INFO - register_us.py[:236] - CinnamoncNilea471@nineboys.club用户注册成功！
2019-07-03 17:46:31,089 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 17:46:35,225 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d4fd61fdea21d2f86c02047970e4357a
2019-07-03 17:46:36,231 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d4fd61fdea21d2f86c02047970e4357a
2019-07-03 17:46:37,234 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d4fd61fdea21d2f86c02047970e4357a
2019-07-03 17:48:40,059 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 17:50:10,431 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 17:51:08,620 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 17:51:15,634 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 17:51:25,700 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 17:51:39,037 - INFO - register_us.py[:236] - CharmainecLaineye390@nineboys.fun用户注册成功！
2019-07-03 17:51:41,221 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 17:51:44,415 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD583C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/caafa0576af41109401278bbe69814e4
2019-07-03 17:51:45,418 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/caafa0576af41109401278bbe69814e4
2019-07-03 17:51:46,420 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/caafa0576af41109401278bbe69814e4
2019-07-03 17:53:11,484 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 17:54:18,970 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 17:55:55,712 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 17:56:05,751 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 17:56:19,719 - INFO - register_us.py[:236] - HarliaLarka814@nineboy.club用户注册成功！
2019-07-03 17:56:20,924 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 17:56:24,592 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68D68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ad68e1826c5777c742705f376c80fce2
2019-07-03 17:56:25,602 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ad68e1826c5777c742705f376c80fce2
2019-07-03 17:56:26,605 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F3A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ad68e1826c5777c742705f376c80fce2
2019-07-03 17:57:43,211 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 17:58:43,876 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 17:58:52,545 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 17:59:02,719 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 17:59:16,598 - INFO - register_us.py[:236] - DionaKandyc215@nineboy.co用户注册成功！
2019-07-03 17:59:18,099 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 17:59:21,223 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930C18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f327de78b884d266b34af3327b83e92d
2019-07-03 17:59:22,262 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9307B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f327de78b884d266b34af3327b83e92d
2019-07-03 17:59:23,258 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f327de78b884d266b34af3327b83e92d
2019-07-03 18:00:59,466 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 18:02:41,210 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 18:07:51,247 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 18:13:03,737 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 18:14:50,236 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 18:16:19,073 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 18:16:30,218 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 18:16:40,339 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 18:16:57,388 - INFO - register_us.py[:236] - PruaWallise078@nineboy.ltd用户注册成功！
2019-07-03 18:16:58,611 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 18:17:02,747 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F3940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/412d7012a6308afaad13d7249bdc7352
2019-07-03 18:17:03,752 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941F60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/412d7012a6308afaad13d7249bdc7352
2019-07-03 18:17:04,753 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941DD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/412d7012a6308afaad13d7249bdc7352
2019-07-03 18:18:23,316 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 18:19:52,368 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 18:20:03,849 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 18:20:14,036 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 18:20:32,888 - INFO - register_us.py[:236] - TrudyeSone197@nineboy.art用户注册成功！
2019-07-03 18:20:34,032 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 18:20:38,541 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f14271489211f0c2700218760ec468c8
2019-07-03 18:20:39,551 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f14271489211f0c2700218760ec468c8
2019-07-03 18:20:40,560 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f14271489211f0c2700218760ec468c8
2019-07-03 18:21:59,730 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 18:23:50,042 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 18:29:01,349 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 18:34:10,579 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 18:39:40,323 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 18:45:12,113 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 18:50:27,007 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 18:51:56,171 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 18:53:31,918 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 18:54:51,284 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 18:56:54,866 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 18:57:59,586 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 18:58:09,243 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 18:58:19,285 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 18:58:37,846 - INFO - register_us.py[:236] - HannaloreaDeronc017@geabest.ltd用户注册成功！
2019-07-03 18:58:39,159 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 18:58:42,279 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB975F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f5d3f9ae4a808cbbcf05c1cadb466b22
2019-07-03 18:58:43,275 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB905C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f5d3f9ae4a808cbbcf05c1cadb466b22
2019-07-03 18:58:44,281 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB907B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f5d3f9ae4a808cbbcf05c1cadb466b22
2019-07-03 19:00:21,266 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 19:01:55,327 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 19:04:01,413 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 19:06:43,272 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 19:09:43,227 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 19:11:10,915 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 19:11:20,948 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 19:11:36,843 - INFO - register_us.py[:236] - RolandcBahiaa217@geabest.info用户注册成功！
2019-07-03 19:11:39,477 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 19:11:43,649 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD682B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e022f4ef6cffe13aab03beb3e09a990
2019-07-03 19:11:44,649 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e022f4ef6cffe13aab03beb3e09a990
2019-07-03 19:11:45,654 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBD68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e022f4ef6cffe13aab03beb3e09a990
2019-07-03 19:17:13,555 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 19:17:19,707 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 19:28:47,931 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 19:30:00,975 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 19:30:11,092 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 19:30:25,551 - INFO - register_us.py[:236] - FelesaaGazellec614@geabest.pro用户注册成功！
2019-07-03 19:30:26,655 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 19:30:29,894 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB97D68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/426bc9d15b46eb7ddcbe4d05f0858aaa
2019-07-03 19:30:30,901 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB977B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/426bc9d15b46eb7ddcbe4d05f0858aaa
2019-07-03 19:30:31,899 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB97DD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/426bc9d15b46eb7ddcbe4d05f0858aaa
2019-07-03 19:33:07,817 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 19:34:36,862 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 19:36:21,009 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 19:36:31,049 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 19:36:47,303 - INFO - register_us.py[:236] - AlbinaeVirginiaa098@geabest.mobi用户注册成功！
2019-07-03 19:36:49,054 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 19:36:53,326 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2d7ac6c22b8d0d87b92a9fdd7d61452b
2019-07-03 19:36:54,328 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91AF98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2d7ac6c22b8d0d87b92a9fdd7d61452b
2019-07-03 19:36:55,332 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2d7ac6c22b8d0d87b92a9fdd7d61452b
2019-07-03 19:42:04,714 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 19:43:23,790 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 19:48:48,715 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 19:50:23,120 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 19:51:31,413 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 19:51:41,603 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 19:51:55,597 - INFO - register_us.py[:236] - MaryonaTima930@geabest.com.cn用户注册成功！
2019-07-03 19:51:57,390 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 19:52:00,646 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90B38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4088b1c2e342542ee2b8205f7343d7d4
2019-07-03 19:52:01,652 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4088b1c2e342542ee2b8205f7343d7d4
2019-07-03 19:52:02,649 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD685F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4088b1c2e342542ee2b8205f7343d7d4
2019-07-03 19:53:14,650 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 19:54:29,756 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 19:56:14,956 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 19:58:06,780 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 19:58:30,350 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 19:58:40,942 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 19:59:01,848 - INFO - register_us.py[:236] - DorotheaaBrinleye678@geabest.cc用户注册成功！
2019-07-03 19:59:05,267 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 19:59:09,408 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68DA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6635b9658d07050390de3d8a412b7363
2019-07-03 19:59:10,509 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6635b9658d07050390de3d8a412b7363
2019-07-03 19:59:11,889 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD685F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6635b9658d07050390de3d8a412b7363
2019-07-03 20:04:29,837 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 20:10:06,325 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 20:13:28,817 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 20:14:31,298 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 20:15:29,825 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 20:15:40,159 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 20:15:54,592 - INFO - register_us.py[:236] - MarcuseOrlandoa386@geabest.online用户注册成功！
2019-07-03 20:15:56,949 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 20:16:00,293 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d79f92ef08fce26a927dd566484c09b
2019-07-03 20:16:01,302 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d79f92ef08fce26a927dd566484c09b
2019-07-03 20:16:02,334 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941BA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0d79f92ef08fce26a927dd566484c09b
2019-07-03 20:17:47,027 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 20:19:59,310 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 20:21:19,543 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 20:21:29,757 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 20:21:55,367 - INFO - register_us.py[:236] - CarlyeDixiea439@geabest.vip用户注册成功！
2019-07-03 20:22:00,581 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 20:22:05,966 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/26587628589fec2f2c169d90367601b2
2019-07-03 20:22:07,867 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/26587628589fec2f2c169d90367601b2
2019-07-03 20:22:09,366 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CB38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/26587628589fec2f2c169d90367601b2
2019-07-03 20:27:32,053 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 20:33:02,161 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 20:38:15,731 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 20:40:05,855 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 20:41:19,229 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 20:41:29,327 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 20:41:44,716 - INFO - register_us.py[:236] - NikoeHarlowa270@geabest.store用户注册成功！
2019-07-03 20:41:46,281 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 20:41:49,414 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/32bd8a57bf2806b94e9bbd250b831253
2019-07-03 20:41:50,417 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F3A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/32bd8a57bf2806b94e9bbd250b831253
2019-07-03 20:41:51,421 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F3780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/32bd8a57bf2806b94e9bbd250b831253
2019-07-03 20:43:05,297 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 20:48:15,976 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 20:50:53,447 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 20:51:48,273 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 20:52:33,669 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 20:52:38,839 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 20:52:48,890 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 20:53:01,467 - INFO - register_us.py[:236] - TamieeAlennaa578@yyw.ltd用户注册成功！
2019-07-03 20:53:02,455 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 20:53:06,671 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941F60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7908acd69c1b6e16b5066246ed191611
2019-07-03 20:53:07,668 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7908acd69c1b6e16b5066246ed191611
2019-07-03 20:53:08,674 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9415F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7908acd69c1b6e16b5066246ed191611
2019-07-03 20:54:41,799 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 20:56:24,612 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 20:56:37,359 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 20:56:47,799 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 20:57:19,018 - INFO - register_us.py[:236] - WyntoncHartwella104@gets.vip用户注册成功！
2019-07-03 20:57:22,597 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 20:57:28,407 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD685F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee6f9f9abe252c906adf318044b9f0b8
2019-07-03 20:57:29,508 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee6f9f9abe252c906adf318044b9f0b8
2019-07-03 20:57:30,907 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee6f9f9abe252c906adf318044b9f0b8
2019-07-03 21:02:54,454 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 21:08:08,984 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 21:13:19,584 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 21:18:43,253 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 21:20:08,384 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 21:22:30,534 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 21:24:03,389 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 21:29:13,374 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 21:31:20,064 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 21:33:08,859 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 21:35:17,297 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 21:36:35,813 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 21:38:14,970 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 21:38:26,568 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 21:38:49,318 - INFO - register_us.py[:236] - TravonaElissae547@yyw.wiki用户注册成功！
2019-07-03 21:38:50,744 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 21:38:55,345 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD686A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/78799d6dbdb2267efb3dc3206e36eef3
2019-07-03 21:38:56,352 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/78799d6dbdb2267efb3dc3206e36eef3
2019-07-03 21:38:57,362 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD586D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/78799d6dbdb2267efb3dc3206e36eef3
2019-07-03 21:44:07,786 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 21:45:44,357 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 21:50:53,728 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 21:56:03,764 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 21:57:41,732 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 21:58:54,894 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 21:59:06,481 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 21:59:16,873 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 21:59:30,415 - INFO - register_us.py[:236] - ClovisaPhilisc287@yyw.link用户注册成功！
2019-07-03 21:59:38,668 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 21:59:43,108 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ca13dca514b6a95d04f07597fe881b06
2019-07-03 21:59:44,245 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD580F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ca13dca514b6a95d04f07597fe881b06
2019-07-03 21:59:45,251 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ca13dca514b6a95d04f07597fe881b06
2019-07-03 22:01:30,848 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 22:05:07,776 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 22:05:17,877 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 22:05:35,252 - INFO - register_us.py[:236] - TalaAbiec650@beads.ren用户注册成功！
2019-07-03 22:05:39,760 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 22:05:45,269 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9308D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3eeda26580e570371641e262f1a588a9
2019-07-03 22:05:46,300 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3eeda26580e570371641e262f1a588a9
2019-07-03 22:05:47,304 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD686A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3eeda26580e570371641e262f1a588a9
2019-07-03 22:07:22,609 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 22:08:55,653 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 22:09:55,672 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 22:10:04,365 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 22:10:14,410 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 22:10:30,213 - INFO - register_us.py[:236] - OgelsvycMelindaa284@beads.ink用户注册成功！
2019-07-03 22:10:36,010 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 22:10:39,167 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d717168185b01d8379cb157b6bf11332
2019-07-03 22:10:40,175 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d717168185b01d8379cb157b6bf11332
2019-07-03 22:10:41,184 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d717168185b01d8379cb157b6bf11332
2019-07-03 22:12:23,463 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 22:13:28,136 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 22:13:38,165 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 22:13:52,102 - INFO - register_us.py[:236] - MarissaeKaraa342@beads.group用户注册成功！
2019-07-03 22:13:54,192 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 22:13:57,374 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD586D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d25207d4195d4e537c37c1e3057d4e13
2019-07-03 22:13:58,377 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d25207d4195d4e537c37c1e3057d4e13
2019-07-03 22:13:59,381 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD580B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d25207d4195d4e537c37c1e3057d4e13
2019-07-03 22:16:13,042 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 22:18:52,751 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 22:21:15,632 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 22:21:25,297 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 22:21:35,478 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 22:22:42,899 - INFO - register_us.py[:236] - ArnoldaNahaliela825@beads.pub用户注册成功！
2019-07-03 22:22:45,193 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 22:22:49,381 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/037886d11415ffab3d7bf04bb8296190
2019-07-03 22:22:50,385 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/037886d11415ffab3d7bf04bb8296190
2019-07-03 22:22:51,393 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/037886d11415ffab3d7bf04bb8296190
2019-07-03 22:24:33,815 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 22:26:10,011 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 22:27:18,162 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 22:29:38,130 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 22:32:44,211 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 22:32:54,247 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 22:33:34,700 - INFO - register_us.py[:236] - SaxonaHayesa143@beads.link用户注册成功！
2019-07-03 22:33:37,744 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 22:33:40,981 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f4c1af194de122f23cda86c413089808
2019-07-03 22:33:41,982 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f4c1af194de122f23cda86c413089808
2019-07-03 22:33:42,980 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68B38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f4c1af194de122f23cda86c413089808
2019-07-03 22:34:53,320 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 22:40:05,717 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 22:42:30,196 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 22:45:29,894 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 22:46:29,708 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 22:46:41,199 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 22:46:51,647 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 22:47:09,612 - INFO - register_us.py[:236] - BreckineWadec764@beads.name用户注册成功！
2019-07-03 22:47:16,339 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 22:47:22,696 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c36d821958bf2462d177cb7710d6a7d9
2019-07-03 22:47:23,748 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c36d821958bf2462d177cb7710d6a7d9
2019-07-03 22:47:25,347 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CBA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c36d821958bf2462d177cb7710d6a7d9
2019-07-03 22:49:08,994 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 22:50:51,022 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 22:52:47,956 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 22:55:10,339 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 22:58:42,900 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-03 23:00:12,758 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 23:01:18,012 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 23:01:28,097 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 23:03:08,387 - INFO - register_us.py[:236] - FrumacPadene819@beads.kim用户注册成功！
2019-07-03 23:03:11,391 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 23:03:16,133 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1df6d6ec9da61db48210b2a7fa7785cf
2019-07-03 23:03:17,325 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CEB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1df6d6ec9da61db48210b2a7fa7785cf
2019-07-03 23:03:18,741 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C6D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1df6d6ec9da61db48210b2a7fa7785cf
2019-07-03 23:05:11,113 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 23:07:36,128 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 23:08:56,376 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 23:10:00,643 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 23:10:09,701 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 23:10:19,738 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 23:10:33,803 - INFO - register_us.py[:236] - PackardeMarlae615@beads.red用户注册成功！
2019-07-03 23:10:36,573 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 23:10:40,759 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930F28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c44a29384ce75e60805f597d2833179c
2019-07-03 23:10:41,758 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c44a29384ce75e60805f597d2833179c
2019-07-03 23:10:42,763 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91AE48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c44a29384ce75e60805f597d2833179c
2019-07-03 23:16:33,217 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-03 23:18:23,273 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 23:19:47,200 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 23:20:50,308 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 23:21:03,624 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 23:21:15,054 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 23:21:32,593 - INFO - register_us.py[:236] - MurphycShirlenee231@anker.site用户注册成功！
2019-07-03 23:21:34,716 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 23:21:46,758 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB903C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7822836a676ed3b2fb321958f13be420
2019-07-03 23:21:48,156 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C3C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7822836a676ed3b2fb321958f13be420
2019-07-03 23:21:49,288 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CA435470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7822836a676ed3b2fb321958f13be420
2019-07-03 23:23:14,297 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-03 23:25:08,478 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-03 23:26:15,899 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-03 23:26:24,599 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-03 23:26:34,643 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-03 23:26:50,314 - INFO - register_us.py[:236] - NorahaEarthac601@anker.wiki用户注册成功！
2019-07-03 23:26:53,281 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-03 23:26:56,873 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d1149cef3088b0f496b45f48f7a0ce32
2019-07-03 23:26:57,878 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d1149cef3088b0f496b45f48f7a0ce32
2019-07-03 23:26:58,884 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d1149cef3088b0f496b45f48f7a0ce32
2019-07-03 23:27:09,084 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 23:39:06,191 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 23:49:20,312 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-03 23:59:25,399 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 00:12:10,733 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 00:22:36,394 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 00:32:39,879 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 00:42:48,360 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 00:53:08,037 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 01:03:13,176 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 01:13:33,095 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 01:26:43,323 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 01:39:35,046 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 01:52:57,143 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 02:03:02,757 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 02:15:54,517 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 02:28:42,959 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 02:41:37,889 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 02:54:32,484 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 03:07:27,017 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 03:17:46,337 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 03:30:56,158 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 03:41:18,916 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 03:51:22,850 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 04:01:57,792 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 04:12:00,320 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 04:25:15,617 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 04:35:17,947 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 04:48:06,847 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 04:58:09,814 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 05:08:29,112 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 05:18:57,831 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 05:31:13,593 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 05:44:26,321 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 05:54:57,680 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:05:00,789 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:15:10,261 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:25:13,633 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:35:18,018 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:45:37,786 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:55:47,939 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:05:50,842 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:15:55,039 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:25:58,444 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:36:01,708 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:46:07,333 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:56:28,043 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 08:06:37,841 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 08:17:03,178 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 08:29:11,181 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 08:39:16,024 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 08:49:19,789 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 09:02:14,562 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 09:12:17,060 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 09:22:25,249 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 09:32:28,560 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 09:42:34,842 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 09:52:39,779 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:02:41,653 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:12:44,683 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:22:47,452 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:32:50,586 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:42:55,119 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:53:00,345 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:03:02,297 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:13:04,498 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:23:24,081 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:33:27,686 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:43:31,582 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:53:35,941 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:03:40,691 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:13:43,846 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:23:48,752 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:33:51,798 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:43:54,047 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:53:56,921 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:04:00,154 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:14:09,530 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:24:12,779 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:34:16,826 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:44:24,420 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:54:33,469 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:04:37,233 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:14:39,685 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:24:42,591 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:34:45,996 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:44:48,620 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:54:55,604 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:04:58,806 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:15:05,526 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:25:08,431 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:35:12,289 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:45:15,008 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:55:17,975 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 16:07:09,069 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-04 16:07:14,494 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 16:19:41,062 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 16:31:02,114 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 16:32:00,842 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 16:32:09,493 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 16:32:19,536 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 16:32:59,726 - INFO - register_us.py[:236] - UtacMyrnac680@nineboy.pro用户注册成功！
2019-07-04 16:33:00,563 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 16:33:04,718 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB51D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4b959b5b170f93225c1e2141209373df
2019-07-04 16:33:05,723 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4b959b5b170f93225c1e2141209373df
2019-07-04 16:33:06,716 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4b959b5b170f93225c1e2141209373df
2019-07-04 16:39:20,767 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-04 16:41:01,140 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 16:42:11,612 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 16:42:21,642 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 16:42:37,305 - INFO - register_us.py[:236] - SophiaaOletac560@nineboy.vip用户注册成功！
2019-07-04 16:42:40,883 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 16:42:45,069 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB54A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3b4249d87d9002bce1b621ee7d0b1ae7
2019-07-04 16:42:46,070 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3b4249d87d9002bce1b621ee7d0b1ae7
2019-07-04 16:42:47,070 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3b4249d87d9002bce1b621ee7d0b1ae7
2019-07-04 16:44:28,328 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-04 16:45:44,321 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
