2019-07-04 16:46:41,287 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 16:46:48,671 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 16:46:58,700 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 16:47:12,404 - INFO - register_us.py[:236] - VailaVersiee032@nineboy.biz用户注册成功！
2019-07-04 16:47:13,386 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 16:47:16,493 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FB588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/79a44aae6d7266ad631e9de7ff54ab15
2019-07-04 16:47:17,507 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD684E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/79a44aae6d7266ad631e9de7ff54ab15
2019-07-04 16:47:18,517 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/79a44aae6d7266ad631e9de7ff54ab15
2019-07-04 16:48:39,435 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 16:49:48,325 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 16:49:58,353 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 16:50:12,684 - INFO - register_us.py[:236] - TieshaaPoloa475@nineboy.net用户注册成功！
2019-07-04 16:50:14,580 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 16:50:18,716 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c19960b1ff4a7e127530729629d36555
2019-07-04 16:50:19,725 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB55F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c19960b1ff4a7e127530729629d36555
2019-07-04 16:50:20,726 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c19960b1ff4a7e127530729629d36555
2019-07-04 16:51:53,980 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 16:53:40,612 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 16:53:46,120 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 16:53:56,164 - INFO - register_us.py[:122] - 个人信息设置失败！failed,Quit!
2019-07-04 16:55:40,096 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 17:05:40,283 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-04 17:07:03,717 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 17:08:00,110 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 17:08:08,602 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 17:08:18,635 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 17:08:33,965 - INFO - register_us.py[:236] - RuebeneLania614@aukey.ltd用户注册成功！
2019-07-04 17:08:35,119 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 17:08:38,303 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD682B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fe6557defcbd6732235cd4597cd48e4e
2019-07-04 17:08:39,319 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91AEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fe6557defcbd6732235cd4597cd48e4e
2019-07-04 17:08:40,366 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fe6557defcbd6732235cd4597cd48e4e
2019-07-04 17:10:03,527 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 17:11:13,023 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 17:11:22,103 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 17:11:32,214 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 17:11:47,393 - INFO - register_us.py[:236] - RubieeVikkia946@aukey.net.cn用户注册成功！
2019-07-04 17:11:55,080 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 17:11:58,266 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9f1f8a33d7e21b2f47e7638f13a9b326
2019-07-04 17:11:59,283 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9f1f8a33d7e21b2f47e7638f13a9b326
2019-07-04 17:12:00,283 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9f1f8a33d7e21b2f47e7638f13a9b326
2019-07-04 17:13:28,915 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 17:14:38,545 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 17:14:48,580 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 17:15:03,239 - INFO - register_us.py[:236] - TressiecUliciaa304@aukey.mobi用户注册成功！
2019-07-04 17:15:04,179 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 17:15:07,299 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/620f7b485a39cbe5052d32548eec7734
2019-07-04 17:15:08,301 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F3AC8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/620f7b485a39cbe5052d32548eec7734
2019-07-04 17:15:09,303 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/620f7b485a39cbe5052d32548eec7734
2019-07-04 17:17:32,958 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 17:20:43,688 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 17:20:53,715 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 17:21:10,403 - INFO - register_us.py[:236] - MattaaTravea805@nineboys.co用户注册成功！
2019-07-04 17:21:15,140 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 17:21:19,336 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB905F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b71443116eddf433d8fa239b5444f722
2019-07-04 17:21:20,340 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b71443116eddf433d8fa239b5444f722
2019-07-04 17:21:21,339 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b71443116eddf433d8fa239b5444f722
2019-07-04 17:23:08,446 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 17:24:11,123 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 17:24:20,335 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 17:24:30,374 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 17:24:44,383 - INFO - register_us.py[:236] - TermoncJonnac029@nineboys.store用户注册成功！
2019-07-04 17:26:12,335 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD689E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5d5ef62eea28681628d3ff7c1dd6397c
2019-07-04 17:26:13,368 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5d5ef62eea28681628d3ff7c1dd6397c
2019-07-04 17:26:14,383 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5d5ef62eea28681628d3ff7c1dd6397c
2019-07-04 17:29:00,671 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 17:41:55,241 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 17:54:53,015 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-04 18:06:15,440 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:07:13,080 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 18:07:20,125 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:07:30,143 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:07:45,646 - INFO - register_us.py[:236] - AphraeAlmae083@nineboys.site用户注册成功！
2019-07-04 18:07:48,877 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:07:53,042 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9dd597b47778e1576d9aacf6ac9cfe3f
2019-07-04 18:07:54,059 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9dd597b47778e1576d9aacf6ac9cfe3f
2019-07-04 18:07:55,075 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB904A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9dd597b47778e1576d9aacf6ac9cfe3f
2019-07-04 18:09:11,717 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:10:16,186 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:10:26,203 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:10:40,721 - INFO - register_us.py[:236] - KathiecBedrose435@nineboys.pro用户注册成功！
2019-07-04 18:10:42,732 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:10:46,870 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2764fcbcbb691d31b0cb55afd02a250d
2019-07-04 18:10:47,871 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2764fcbcbb691d31b0cb55afd02a250d
2019-07-04 18:10:48,871 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2764fcbcbb691d31b0cb55afd02a250d
2019-07-04 18:12:03,617 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:13:02,833 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:13:12,900 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:13:26,546 - INFO - register_us.py[:236] - RonaldaDawa691@nineboys.org用户注册成功！
2019-07-04 18:13:27,587 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:13:30,740 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CA435BA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8bf8658402292d464abf7757d5917021
2019-07-04 18:13:31,772 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941BA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8bf8658402292d464abf7757d5917021
2019-07-04 18:13:32,787 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8bf8658402292d464abf7757d5917021
2019-07-04 18:14:54,326 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:16:01,150 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:16:11,186 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:16:25,072 - INFO - register_us.py[:236] - ValarieaBudc435@nineboys.info用户注册成功！
2019-07-04 18:16:26,217 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:16:30,363 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C4A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bbe3e2a6004aa0be8530be3e64d121a9
2019-07-04 18:16:31,371 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB57F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bbe3e2a6004aa0be8530be3e64d121a9
2019-07-04 18:16:32,370 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bbe3e2a6004aa0be8530be3e64d121a9
2019-07-04 18:17:57,752 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:19:07,933 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:19:17,964 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:19:33,602 - INFO - register_us.py[:236] - RitchieaObeda143@nineboys.top用户注册成功！
2019-07-04 18:19:34,657 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:19:37,846 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a4b27be366ff3ec069d5a23478f256c4
2019-07-04 18:19:38,861 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a4b27be366ff3ec069d5a23478f256c4
2019-07-04 18:19:39,857 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD715C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a4b27be366ff3ec069d5a23478f256c4
2019-07-04 18:21:00,845 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:22:10,602 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 18:22:19,986 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:22:30,034 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:22:47,676 - INFO - register_us.py[:236] - CaelcPaisleee506@nineboys.tech用户注册成功！
2019-07-04 18:22:49,767 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:22:52,899 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB900B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fcd7e74569d2c3ba44861f4379023f54
2019-07-04 18:22:53,932 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A4A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fcd7e74569d2c3ba44861f4379023f54
2019-07-04 18:22:54,932 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91AE48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fcd7e74569d2c3ba44861f4379023f54
2019-07-04 18:24:06,676 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:25:05,732 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:25:15,769 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:25:29,555 - INFO - register_us.py[:236] - EmileVinniee530@nineboys.ltd用户注册成功！
2019-07-04 18:25:32,632 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:25:35,742 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FB588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d5dff68e1e56d55b3da8601f2fc30299
2019-07-04 18:25:36,744 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CA42AC18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d5dff68e1e56d55b3da8601f2fc30299
2019-07-04 18:25:37,759 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD71860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d5dff68e1e56d55b3da8601f2fc30299
2019-07-04 18:26:49,218 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-04 18:28:06,714 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-04 18:29:47,099 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:30:52,708 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:31:02,752 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:31:17,111 - INFO - register_us.py[:236] - ElwincPriscillac517@nineboys.group用户注册成功！
2019-07-04 18:31:19,072 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:31:23,223 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b82c6e62eb554a95e8bb006e4cdf15f1
2019-07-04 18:31:24,223 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b82c6e62eb554a95e8bb006e4cdf15f1
2019-07-04 18:31:25,222 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b82c6e62eb554a95e8bb006e4cdf15f1
2019-07-04 18:33:38,065 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:34:46,016 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:34:56,060 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:35:10,401 - INFO - register_us.py[:236] - FirmanaMelinae091@nineboys.xyz用户注册成功！
2019-07-04 18:35:11,445 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:35:14,620 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d917df1f0f9ca168ecd69837bb6cf8f2
2019-07-04 18:35:15,619 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d917df1f0f9ca168ecd69837bb6cf8f2
2019-07-04 18:35:16,617 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d917df1f0f9ca168ecd69837bb6cf8f2
2019-07-04 18:36:48,894 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:37:57,946 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:38:07,975 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:38:24,866 - INFO - register_us.py[:236] - GaetaneeOrpaha951@nineboys.cn用户注册成功！
2019-07-04 18:38:25,973 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:38:29,123 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1421eb8048082d81c4cc5bd83501c295
2019-07-04 18:38:30,121 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBF98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1421eb8048082d81c4cc5bd83501c295
2019-07-04 18:38:31,122 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBA58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1421eb8048082d81c4cc5bd83501c295
2019-07-04 18:40:07,798 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:41:16,823 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:41:26,864 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:41:57,680 - INFO - register_us.py[:236] - VondacMaraha901@nineboys.club用户注册成功！
2019-07-04 18:42:16,907 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:42:20,064 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6d0e13aff1978efec8e7165bd2c52a55
2019-07-04 18:42:21,096 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9307F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6d0e13aff1978efec8e7165bd2c52a55
2019-07-04 18:42:22,112 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6d0e13aff1978efec8e7165bd2c52a55
2019-07-04 18:43:37,442 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:44:36,906 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 18:44:46,032 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:44:56,065 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:45:11,090 - INFO - register_us.py[:236] - ArdysaGabriellac814@nineboys.fun用户注册成功！
2019-07-04 18:45:12,466 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:45:16,593 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e38ae55f8d2a780983e32ad362f9cc86
2019-07-04 18:45:17,593 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e38ae55f8d2a780983e32ad362f9cc86
2019-07-04 18:45:18,594 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD584E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e38ae55f8d2a780983e32ad362f9cc86
2019-07-04 18:46:38,708 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:47:38,468 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 18:47:46,271 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:47:56,304 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:48:10,519 - INFO - register_us.py[:236] - VivianaeTaia546@nineboy.club用户注册成功！
2019-07-04 18:48:11,645 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:48:14,803 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD587F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/67231bdaa24cb9b1cb41126d29662390
2019-07-04 18:48:15,804 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/67231bdaa24cb9b1cb41126d29662390
2019-07-04 18:48:16,820 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBB38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/67231bdaa24cb9b1cb41126d29662390
2019-07-04 18:49:36,798 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:50:48,433 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:50:58,474 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:51:14,336 - INFO - register_us.py[:236] - AustincBayarde905@nineboy.co用户注册成功！
2019-07-04 18:51:15,218 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:51:18,393 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/433f71139b64113a9a38a5e2d429dacb
2019-07-04 18:51:19,393 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/433f71139b64113a9a38a5e2d429dacb
2019-07-04 18:51:20,408 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/433f71139b64113a9a38a5e2d429dacb
2019-07-04 18:52:42,087 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:53:43,887 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 18:53:51,909 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:54:01,929 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:54:15,764 - INFO - register_us.py[:236] - IdaniaeLarvalla456@nineboy.store用户注册成功！
2019-07-04 18:54:16,965 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:54:20,092 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBB90828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ae1c00cf6436b5cd97e0c2db094b729f
2019-07-04 18:54:21,109 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ae1c00cf6436b5cd97e0c2db094b729f
2019-07-04 18:54:22,140 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ae1c00cf6436b5cd97e0c2db094b729f
2019-07-04 18:55:47,797 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:56:49,937 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:56:59,974 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:57:15,193 - INFO - register_us.py[:236] - DamianaJessea324@nineboy.group用户注册成功！
2019-07-04 18:57:16,069 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 18:57:19,225 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a54e854b5fcf045b9aa135fed2a4ab73
2019-07-04 18:57:20,242 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a54e854b5fcf045b9aa135fed2a4ab73
2019-07-04 18:57:21,242 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBF98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a54e854b5fcf045b9aa135fed2a4ab73
2019-07-04 18:58:32,942 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 18:59:25,416 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 18:59:34,876 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 18:59:44,902 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 18:59:59,187 - INFO - register_us.py[:236] - QueenettacLanzae801@nineboy.ltd用户注册成功！
2019-07-04 19:00:00,191 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:00:04,349 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8fed377dd7e423faf2c3b600158160ce
2019-07-04 19:00:05,366 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68B38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8fed377dd7e423faf2c3b600158160ce
2019-07-04 19:00:06,397 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8fed377dd7e423faf2c3b600158160ce
2019-07-04 19:01:13,893 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-04 19:03:33,349 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:04:34,359 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-04 19:06:04,517 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:07:11,036 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 19:07:18,984 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:07:29,028 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:07:44,883 - INFO - register_us.py[:236] - EdmondeJordanaa673@nineboy.art用户注册成功！
2019-07-04 19:07:45,679 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:07:48,868 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b0ab2fb965cdbbfab0530a7e4056bdff
2019-07-04 19:07:49,883 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b0ab2fb965cdbbfab0530a7e4056bdff
2019-07-04 19:07:50,916 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB58D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b0ab2fb965cdbbfab0530a7e4056bdff
2019-07-04 19:09:08,277 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:10:10,844 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:10:20,888 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:10:34,901 - INFO - register_us.py[:236] - HarlowaEstellae836@geabest.club用户注册成功！
2019-07-04 19:10:39,008 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:10:42,159 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB57F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/20400d929a26f17da79f7011905f9231
2019-07-04 19:10:43,175 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/20400d929a26f17da79f7011905f9231
2019-07-04 19:10:44,191 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/20400d929a26f17da79f7011905f9231
2019-07-04 19:12:36,138 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:14:25,680 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:14:35,716 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:14:49,568 - INFO - register_us.py[:236] - HankcAmiela164@geabest.ltd用户注册成功！
2019-07-04 19:14:52,497 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:14:56,656 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f6e5a2f044b5e9b5b36e7e88fbbf981b
2019-07-04 19:14:57,672 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f6e5a2f044b5e9b5b36e7e88fbbf981b
2019-07-04 19:14:58,672 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9301D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f6e5a2f044b5e9b5b36e7e88fbbf981b
2019-07-04 19:15:07,895 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 19:26:52,406 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-04 19:29:32,860 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-04 19:30:48,973 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:31:49,855 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:31:59,895 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:32:16,770 - INFO - register_us.py[:236] - CartereEnoche875@geabest.info用户注册成功！
2019-07-04 19:32:17,701 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:32:20,829 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ab0069c450555fbcdee5bcbef276d8b4
2019-07-04 19:32:21,845 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ab0069c450555fbcdee5bcbef276d8b4
2019-07-04 19:32:22,859 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ab0069c450555fbcdee5bcbef276d8b4
2019-07-04 19:33:39,111 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:34:44,297 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:34:54,341 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:35:08,102 - INFO - register_us.py[:236] - UisteanaMandela831@geabest.pro用户注册成功！
2019-07-04 19:35:09,552 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:35:12,735 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/71731b329881c29d97873073c70d51c3
2019-07-04 19:35:13,766 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68278>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/71731b329881c29d97873073c70d51c3
2019-07-04 19:35:14,782 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/71731b329881c29d97873073c70d51c3
2019-07-04 19:36:36,502 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:37:45,096 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:37:55,139 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:38:09,464 - INFO - register_us.py[:236] - ZoryercClaudiae163@geabest.mobi用户注册成功！
2019-07-04 19:38:10,545 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:38:13,702 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/04ba779e4eac39db42dc06ce6bdc50a6
2019-07-04 19:38:14,703 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A7B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/04ba779e4eac39db42dc06ce6bdc50a6
2019-07-04 19:38:15,703 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/04ba779e4eac39db42dc06ce6bdc50a6
2019-07-04 19:39:32,724 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:40:37,073 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:40:47,133 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:41:02,929 - INFO - register_us.py[:236] - DanteeAnnaliesee640@geabest.com.cn用户注册成功！
2019-07-04 19:41:04,857 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:41:08,030 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/26a970a2c578a6664ac567607c3ab821
2019-07-04 19:41:09,047 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/26a970a2c578a6664ac567607c3ab821
2019-07-04 19:41:10,062 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CA4356D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/26a970a2c578a6664ac567607c3ab821
2019-07-04 19:42:26,292 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-04 19:43:44,111 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:44:40,090 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 19:44:48,402 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:44:58,436 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:45:14,048 - INFO - register_us.py[:236] - LondonaZebudaha621@geabest.cc用户注册成功！
2019-07-04 19:45:15,752 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:45:19,927 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD689B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e8513e9104f607094d22bde9670b2d3a
2019-07-04 19:45:20,943 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F3978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e8513e9104f607094d22bde9670b2d3a
2019-07-04 19:45:21,943 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e8513e9104f607094d22bde9670b2d3a
2019-07-04 19:46:48,246 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:48:56,590 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:49:06,814 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:49:26,219 - INFO - register_us.py[:236] - MargueritecEthelyne701@geabest.online用户注册成功！
2019-07-04 19:49:27,405 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:49:30,743 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD683C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8cd7304bbbc9238a85c40578dfb292f7
2019-07-04 19:49:31,822 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F3940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8cd7304bbbc9238a85c40578dfb292f7
2019-07-04 19:49:32,844 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F3EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8cd7304bbbc9238a85c40578dfb292f7
2019-07-04 19:50:46,578 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:51:45,384 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:51:55,503 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:52:09,782 - INFO - register_us.py[:236] - RaniacAlyssaa294@geabest.vip用户注册成功！
2019-07-04 19:52:11,263 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:52:16,991 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBDD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b703b04cf378cfb1f20cabb82926cd72
2019-07-04 19:52:17,987 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBE48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b703b04cf378cfb1f20cabb82926cd72
2019-07-04 19:52:19,046 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b703b04cf378cfb1f20cabb82926cd72
2019-07-04 19:53:54,134 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 19:55:37,502 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 19:55:56,458 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 19:56:07,250 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 19:56:24,647 - INFO - register_us.py[:236] - WillardcVelvete487@geabest.store用户注册成功！
2019-07-04 19:56:37,534 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 19:56:44,338 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/47122ed21cbb353746968f97aabb7b25
2019-07-04 19:56:45,357 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/47122ed21cbb353746968f97aabb7b25
2019-07-04 19:56:46,439 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/47122ed21cbb353746968f97aabb7b25
2019-07-04 19:58:49,540 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:00:24,892 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 20:00:38,893 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:00:48,933 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:01:04,589 - INFO - register_us.py[:236] - AbecOcelfae450@yyw.ltd用户注册成功！
2019-07-04 20:01:07,155 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:01:11,359 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB57B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3448fda503be48a748cab346cd6159b3
2019-07-04 20:01:12,438 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB52E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3448fda503be48a748cab346cd6159b3
2019-07-04 20:01:13,537 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F3668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3448fda503be48a748cab346cd6159b3
2019-07-04 20:03:47,661 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:04:53,994 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 20:05:02,642 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:05:12,682 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:05:53,027 - INFO - register_us.py[:236] - AureleaaZakharye619@gets.vip用户注册成功！
2019-07-04 20:05:55,153 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:05:59,311 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/348872019e8139abad4a76fa993664c0
2019-07-04 20:06:00,436 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/348872019e8139abad4a76fa993664c0
2019-07-04 20:06:01,671 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/348872019e8139abad4a76fa993664c0
2019-07-04 20:10:43,751 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:12:09,533 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 20:12:21,659 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:12:31,702 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:13:10,702 - INFO - register_us.py[:236] - NadieracHorsta298@gets.fun用户注册成功！
2019-07-04 20:13:11,887 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:13:16,067 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a14ae5d25d8aa878ccf271c3a4f93786
2019-07-04 20:13:17,067 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5F28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a14ae5d25d8aa878ccf271c3a4f93786
2019-07-04 20:13:18,073 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB59B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a14ae5d25d8aa878ccf271c3a4f93786
2019-07-04 20:14:52,352 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:16:16,647 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 20:16:34,717 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:16:48,042 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:17:08,132 - INFO - register_us.py[:236] - DamiacBritanya741@yyw.wiki用户注册成功！
2019-07-04 20:17:10,467 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:17:16,447 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/123111ee8b730a40be42d7d3d6a150b5
2019-07-04 20:17:17,641 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD680F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/123111ee8b730a40be42d7d3d6a150b5
2019-07-04 20:17:19,341 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD689B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/123111ee8b730a40be42d7d3d6a150b5
2019-07-04 20:19:16,776 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:20:34,455 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 20:20:45,386 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:20:55,741 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:21:11,071 - INFO - register_us.py[:236] - FerguseJolandae427@yyw.link用户注册成功！
2019-07-04 20:21:15,901 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:21:20,207 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cb52f52bbbcf8304a15d0742bb768031
2019-07-04 20:21:21,365 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5C18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cb52f52bbbcf8304a15d0742bb768031
2019-07-04 20:21:22,407 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cb52f52bbbcf8304a15d0742bb768031
2019-07-04 20:23:00,121 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:24:03,588 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 20:24:09,266 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:24:19,305 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:24:33,091 - INFO - register_us.py[:236] - GarrettaEditha308@beads.ren用户注册成功！
2019-07-04 20:24:35,832 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:24:39,124 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB930D68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f90c09457f98285b9e4113bb01eed460
2019-07-04 20:24:41,117 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8F36A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f90c09457f98285b9e4113bb01eed460
2019-07-04 20:24:42,456 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f90c09457f98285b9e4113bb01eed460
2019-07-04 20:25:59,056 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-04 20:28:20,988 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-04 20:29:54,197 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:30:54,545 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 20:31:03,236 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:31:13,288 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:31:28,431 - INFO - register_us.py[:236] - DaynacValmaie294@beads.ink用户注册成功！
2019-07-04 20:31:29,484 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:31:32,653 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bc1b97c3404e3a937897ca1ea3745ea4
2019-07-04 20:31:33,677 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bc1b97c3404e3a937897ca1ea3745ea4
2019-07-04 20:31:34,682 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9415F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bc1b97c3404e3a937897ca1ea3745ea4
2019-07-04 20:35:04,673 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-04 20:41:21,014 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-04 20:43:04,069 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:44:13,821 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:44:23,903 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:44:38,807 - INFO - register_us.py[:236] - CredaeBarsabasa948@beads.group用户注册成功！
2019-07-04 20:44:39,747 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:44:43,916 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cf10ef7707c823eab2c25d40b6ffad47
2019-07-04 20:44:44,922 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CCC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cf10ef7707c823eab2c25d40b6ffad47
2019-07-04 20:44:46,025 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CC18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cf10ef7707c823eab2c25d40b6ffad47
2019-07-04 20:46:12,127 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:47:25,188 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:47:35,227 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:47:49,844 - INFO - register_us.py[:236] - TabaIdaniaa769@beads.pub用户注册成功！
2019-07-04 20:47:57,216 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:48:01,028 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5AC8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7c31302c5746642d809e5684fca34f29
2019-07-04 20:48:02,051 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7c31302c5746642d809e5684fca34f29
2019-07-04 20:48:03,138 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB941A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7c31302c5746642d809e5684fca34f29
2019-07-04 20:49:43,734 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:50:59,786 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 20:51:10,950 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:51:21,249 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:51:37,571 - INFO - register_us.py[:236] - PaisleecJanee102@beads.wang用户注册成功！
2019-07-04 20:51:38,931 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:51:42,098 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FB898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5349af6dee93b5f3057da41589a8aa2b
2019-07-04 20:51:43,101 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5349af6dee93b5f3057da41589a8aa2b
2019-07-04 20:51:44,099 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5349af6dee93b5f3057da41589a8aa2b
2019-07-04 20:53:21,553 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:54:23,780 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 20:54:33,835 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:54:43,883 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:54:59,157 - INFO - register_us.py[:236] - MayaeAbdula872@beads.link用户注册成功！
2019-07-04 20:55:01,495 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:55:04,716 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C9E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f2389dab36fa75f0cfe6db69a3a4d2fe
2019-07-04 20:55:05,718 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f2389dab36fa75f0cfe6db69a3a4d2fe
2019-07-04 20:55:06,723 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FBA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f2389dab36fa75f0cfe6db69a3a4d2fe
2019-07-04 20:56:31,123 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 20:57:39,843 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 20:57:51,313 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 20:58:01,486 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 20:58:18,936 - INFO - register_us.py[:236] - GardcXeniaa976@beads.name用户注册成功！
2019-07-04 20:58:20,437 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 20:58:24,017 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C6D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a9bee2de52d0cd10e1eca94f9262016c
2019-07-04 20:58:25,418 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a9bee2de52d0cd10e1eca94f9262016c
2019-07-04 20:58:26,861 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a9bee2de52d0cd10e1eca94f9262016c
2019-07-04 21:00:08,308 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 21:01:26,553 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 21:01:36,604 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 21:01:50,934 - INFO - register_us.py[:236] - TripcAgnesc194@beads.kim用户注册成功！
2019-07-04 21:01:53,763 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 21:01:57,939 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3be1fcf12294894fe606992805798aad
2019-07-04 21:01:58,948 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD58DD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3be1fcf12294894fe606992805798aad
2019-07-04 21:01:59,948 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD587F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3be1fcf12294894fe606992805798aad
2019-07-04 21:03:21,007 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 21:04:36,886 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 21:04:46,926 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 21:05:01,904 - INFO - register_us.py[:236] - PeronelaUaida519@beads.red用户注册成功！
2019-07-04 21:05:10,156 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 21:05:13,616 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FB860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4bed53427b303e6bd2334278a9ad1ef1
2019-07-04 21:05:14,619 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4bed53427b303e6bd2334278a9ad1ef1
2019-07-04 21:05:15,618 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4bed53427b303e6bd2334278a9ad1ef1
2019-07-04 21:06:39,235 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 21:07:48,579 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-04 21:09:08,990 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 21:10:08,038 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-04 21:10:16,715 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 21:10:26,755 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 21:10:40,682 - INFO - register_us.py[:236] - BensoneClovera716@anker.site用户注册成功！
2019-07-04 21:10:43,841 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 21:10:47,965 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD582E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b946b67d62b70ba0f827e2e17e2080f2
2019-07-04 21:10:48,972 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b946b67d62b70ba0f827e2e17e2080f2
2019-07-04 21:10:49,980 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB9414A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b946b67d62b70ba0f827e2e17e2080f2
2019-07-04 21:12:01,286 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 21:12:55,934 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 21:13:05,970 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 21:13:18,502 - INFO - register_us.py[:236] - BetsycImogenee432@anker.wiki用户注册成功！
2019-07-04 21:13:20,333 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 21:13:24,488 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/03839d1919a9dff0e6feda99e5429c62
2019-07-04 21:13:25,485 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/03839d1919a9dff0e6feda99e5429c62
2019-07-04 21:13:26,495 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4C128>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/03839d1919a9dff0e6feda99e5429c62
2019-07-04 21:14:46,054 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 21:15:53,586 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 21:16:03,619 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 21:16:18,636 - INFO - register_us.py[:236] - VestacRagnare631@anker.work用户注册成功！
2019-07-04 21:16:19,903 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 21:16:24,118 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2bea83941e0f2778c40208cd21e378f5
2019-07-04 21:16:25,117 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2bea83941e0f2778c40208cd21e378f5
2019-07-04 21:16:26,120 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBBB5438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/2bea83941e0f2778c40208cd21e378f5
2019-07-04 21:18:24,829 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 21:19:38,420 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 21:19:48,460 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 21:20:04,273 - INFO - register_us.py[:236] - RosscBirdiea613@shein.xin用户注册成功！
2019-07-04 21:20:06,067 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 21:20:10,289 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD68C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/41f29d51bdc2720b578cd2c250bf7f9b
2019-07-04 21:20:11,289 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB8FB588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/41f29d51bdc2720b578cd2c250bf7f9b
2019-07-04 21:20:12,294 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/41f29d51bdc2720b578cd2c250bf7f9b
2019-07-04 21:22:46,784 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-04 21:24:16,217 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 21:25:25,640 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 21:25:35,677 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 21:25:51,692 - INFO - register_us.py[:236] - MiltaLangstona615@shein.wang用户注册成功！
2019-07-04 21:25:56,069 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-04 21:26:00,198 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CB91A048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5068c8b9ba8c8c32918fc3562741c101
2019-07-04 21:26:01,202 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CBD4CC18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5068c8b9ba8c8c32918fc3562741c101
2019-07-04 21:26:02,205 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000068CA435BA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5068c8b9ba8c8c32918fc3562741c101
2019-07-04 21:26:07,610 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 21:37:14,475 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-04 21:38:34,069 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-04 21:39:42,086 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-04 21:39:52,121 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-04 21:40:06,501 - INFO - register_us.py[:236] - MurphycLaurentc870@shein.kim用户注册成功！
2019-07-04 21:40:08,414 - INFO - register_us.py[:270] - 注册信息已成功入库！
