2019-07-09 00:31:39,078 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-09 00:31:46,661 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-09 00:31:56,685 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-09 00:32:10,355 - INFO - register_us.py[:236] - KathleeneTaffya943@nineboy.net用户注册成功！
2019-07-09 00:32:12,488 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-09 00:32:16,641 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3DEA0FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/83684e9bf1f83544b190ab6270813147
2019-07-09 00:32:17,656 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3D3E95F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/83684e9bf1f83544b190ab6270813147
2019-07-09 00:32:18,672 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3DEA0588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/83684e9bf1f83544b190ab6270813147
2019-07-09 00:33:56,205 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-09 00:35:30,096 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-09 00:38:43,109 - INFO - register_us.py[:145] - 注册出错，程序结束！
2019-07-09 00:39:57,454 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-09 00:40:55,447 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-09 00:41:05,467 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-09 00:41:17,981 - INFO - register_us.py[:236] - DennisaWandae871@nineboy.cc用户注册成功！
2019-07-09 00:41:19,510 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-09 00:41:23,650 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3E4AFD30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9d8052b17f89941b5c5b2eec64d31425
2019-07-09 00:41:24,667 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3DEA04E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9d8052b17f89941b5c5b2eec64d31425
2019-07-09 00:41:25,683 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3DEA0BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9d8052b17f89941b5c5b2eec64d31425
2019-07-09 00:42:37,292 - INFO - register_us.py[:149] - 等待超时，程序终止！
2019-07-09 00:45:28,449 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-09 00:47:52,425 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-09 00:48:02,472 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-09 00:48:52,129 - INFO - register_us.py[:236] - DianthaaEmeryc836@aukey.online用户注册成功！
2019-07-09 00:48:58,264 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-09 00:49:01,422 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3E4AFDD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/38f34c84373d99ab6efb8ac7cac5ad38
2019-07-09 00:49:02,453 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3E4AF6A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/38f34c84373d99ab6efb8ac7cac5ad38
2019-07-09 00:49:03,469 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3E4AF780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/38f34c84373d99ab6efb8ac7cac5ad38
2019-07-09 00:50:21,080 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-09 00:51:07,730 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-09 00:51:15,928 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-09 00:51:25,962 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-09 00:51:38,720 - INFO - register_us.py[:236] - AbiacYuria504@aukey.live用户注册成功！
2019-07-09 00:51:40,765 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-09 00:51:43,903 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3DEA69B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6500a1933872d30421c0ce971802bc51
2019-07-09 00:51:44,903 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3DEA6E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6500a1933872d30421c0ce971802bc51
2019-07-09 00:51:45,903 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3D401E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6500a1933872d30421c0ce971802bc51
2019-07-09 00:53:18,451 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-09 00:54:19,308 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-09 00:54:29,330 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-09 00:54:44,516 - INFO - register_us.py[:236] - JoeycRicae902@aukey.fun用户注册成功！
2019-07-09 00:54:49,730 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-09 00:54:52,922 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3D647E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d85de936c6449b8865bf271f3fb095c8
2019-07-09 00:54:53,922 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3D6475F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d85de936c6449b8865bf271f3fb095c8
2019-07-09 00:54:54,939 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3D647668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d85de936c6449b8865bf271f3fb095c8
2019-07-09 00:55:06,115 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 01:05:14,528 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 01:14:24,619 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 01:24:35,479 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 01:34:43,449 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 01:45:13,553 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 01:55:16,661 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 02:05:39,981 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 02:15:58,564 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 02:26:03,532 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 02:36:16,472 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 02:46:18,831 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 02:56:22,361 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 03:06:25,625 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 03:16:41,895 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 03:26:44,644 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 03:36:51,864 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 03:46:59,599 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 03:57:18,932 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 04:07:21,634 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 04:17:41,031 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 04:27:45,109 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 04:37:49,797 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 04:47:58,718 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 04:58:00,796 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 05:08:04,763 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 05:18:07,715 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 05:28:10,792 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 05:38:13,276 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 05:48:17,009 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 05:58:29,559 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 06:08:40,139 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 06:18:42,059 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 06:28:44,558 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 06:38:46,979 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 06:48:56,684 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 06:59:01,933 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 07:09:07,089 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 07:19:12,152 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 07:29:15,167 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 07:39:20,901 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 07:49:24,822 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 07:59:27,477 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 08:09:33,258 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 08:19:36,007 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 08:29:39,006 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 08:39:42,740 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 08:49:46,192 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 08:59:49,160 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 09:09:57,208 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 09:20:01,786 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 09:30:11,024 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 09:40:14,963 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 09:50:51,816 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 10:00:54,439 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 10:10:58,345 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 10:21:22,496 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 10:31:40,124 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 10:42:01,272 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 10:52:08,648 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 10:53:16,050 - INFO - register_us.py[:346] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 10:59:23,374 - INFO - register_us.py[:311] - 个人信息设置失败！failed,Quit!
2019-07-09 10:59:24,077 - INFO - register_us.py[:347] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 11:02:20,103 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 11:12:23,443 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 11:22:26,385 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 11:32:29,275 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 11:42:37,041 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 11:52:40,072 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 12:02:48,620 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 12:13:24,069 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 12:23:39,604 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 12:33:51,248 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 12:43:54,200 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 12:54:22,506 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 13:04:26,897 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 13:14:31,724 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 13:24:38,881 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 13:34:40,863 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 13:44:47,364 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 13:52:15,331 - INFO - register_us.py[:346] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 13:54:51,379 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 14:05:18,184 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 14:15:27,155 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 14:25:30,780 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 14:35:32,887 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 14:45:35,948 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 14:55:38,510 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 15:05:41,134 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 15:16:08,298 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 15:29:02,893 - INFO - register_us.py[:347] - 任务系统出错，程序[sleep 10m]...
2019-07-09 15:39:14,240 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 15:49:20,537 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 15:59:23,036 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 16:09:28,457 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 16:19:35,707 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 16:29:40,019 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 16:39:43,112 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 16:49:46,315 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 16:59:48,953 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 17:09:56,142 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 17:20:36,296 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 17:30:47,315 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 17:40:51,470 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 17:51:06,943 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 18:01:09,395 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 18:12:35,116 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 18:22:41,460 - INFO - register_us.py[:344] - 当前无注册任务，程序[sleep 10m]...
2019-07-09 18:33:52,107 - INFO - register_us.py[:154] - 正在设置用户的基本信息...
2019-07-09 18:34:39,760 - INFO - register_us.py[:215] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-09 18:34:46,966 - INFO - register_us.py[:231] - 点击提交个人信息的设置!
2019-07-09 18:34:56,991 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-09 18:35:09,882 - INFO - register_us.py[:236] - FordeRanea853@aukey.ltd用户注册成功！
2019-07-09 18:35:26,675 - INFO - register_us.py[:270] - 注册信息已成功入库！
2019-07-09 18:35:29,879 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3D401978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/45182277001611fae2586567b106211f
2019-07-09 18:35:30,895 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3DEA6A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/45182277001611fae2586567b106211f
2019-07-09 18:35:31,911 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000004A3D3E94A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/45182277001611fae2586567b106211f
2019-07-11 16:19:38,855 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 16:19:54,405 - INFO - register_us.py[:347] - 当前无注册任务，程序[sleep 10m]...
2019-07-11 16:22:17,477 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:23:19,836 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:23:29,867 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:23:44,539 - INFO - register_us.py[:239] - MeyercMurrayc592@aukey.net.cn用户注册成功！
2019-07-11 16:24:01,116 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:24:04,295 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29203C7B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1714a7bed94331b0134786e0c8795cac
2019-07-11 16:24:05,297 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244D1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1714a7bed94331b0134786e0c8795cac
2019-07-11 16:24:06,297 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244D240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1714a7bed94331b0134786e0c8795cac
2019-07-11 16:26:48,566 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:28:19,229 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 16:28:28,006 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:28:38,040 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:29:07,348 - INFO - register_us.py[:239] - EvaaXimenesa425@aukey.mobi用户注册成功！
2019-07-11 16:29:16,759 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:29:19,874 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292032550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b07be3e3c2cb3ecc3a6316524fb0cab4
2019-07-11 16:29:20,879 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29245EDD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b07be3e3c2cb3ecc3a6316524fb0cab4
2019-07-11 16:29:21,883 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29245E6D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b07be3e3c2cb3ecc3a6316524fb0cab4
2019-07-11 16:29:57,729 - INFO - register_us.py[:347] - 当前无注册任务，程序[sleep 10m]...
2019-07-11 16:30:37,768 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:31:40,430 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:31:50,463 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:32:05,651 - INFO - register_us.py[:239] - AdieJamalc027@nineboys.co用户注册成功！
2019-07-11 16:32:27,694 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:32:31,922 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2920326D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d57517bf1b4a011bf3e465450aad2978
2019-07-11 16:32:32,927 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244DB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d57517bf1b4a011bf3e465450aad2978
2019-07-11 16:32:33,933 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244DEB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d57517bf1b4a011bf3e465450aad2978
2019-07-11 16:34:26,207 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:35:37,184 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 16:35:47,613 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:35:57,645 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:36:14,668 - INFO - register_us.py[:239] - TroryaAlbanya807@nineboys.store用户注册成功！
2019-07-11 16:37:04,530 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:37:08,753 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29245E0B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0723350893919e5299bc3eba8eaae4cd
2019-07-11 16:37:09,755 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29246D9E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0723350893919e5299bc3eba8eaae4cd
2019-07-11 16:37:10,757 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C291FFC828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0723350893919e5299bc3eba8eaae4cd
2019-07-11 16:41:17,612 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:41:38,755 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 16:42:12,500 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 16:42:20,543 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:42:30,577 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:42:45,591 - INFO - register_us.py[:239] - KalindaaUlmarre506@nineboys.art用户注册成功！
2019-07-11 16:43:13,341 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:43:16,499 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DFAEEB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/60af9dfb53bf83fa77dc205f5d42ccae
2019-07-11 16:43:17,502 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DFAE9B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/60af9dfb53bf83fa77dc205f5d42ccae
2019-07-11 16:43:18,529 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DFAEC18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/60af9dfb53bf83fa77dc205f5d42ccae
2019-07-11 16:43:29,733 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:45:15,372 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 16:45:23,517 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:45:33,558 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:45:54,861 - INFO - register_us.py[:239] - QuennelleKolee816@nineboys.art用户注册成功！
2019-07-11 16:45:55,671 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:45:59,797 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:46:02,971 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244DEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/13c15b4e14c1f7d53ff9cf7d823193dc
2019-07-11 16:46:03,980 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244DDD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/13c15b4e14c1f7d53ff9cf7d823193dc
2019-07-11 16:46:04,988 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244D8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/13c15b4e14c1f7d53ff9cf7d823193dc
2019-07-11 16:47:23,717 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:47:48,793 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 16:47:59,435 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:48:09,477 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:48:22,025 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 16:48:30,747 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:48:40,791 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:48:48,463 - INFO - register_us.py[:239] - CatherinecMarciac658@nineboys.site用户注册成功！
2019-07-11 16:48:54,172 - INFO - register_us.py[:239] - TullycBarbarya042@nineboys.site用户注册成功！
2019-07-11 16:48:56,094 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:49:00,282 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29201AF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7f40d5b42e2761665471f1f5dc4eec81
2019-07-11 16:49:01,312 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29201A470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7f40d5b42e2761665471f1f5dc4eec81
2019-07-11 16:49:02,340 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C291FFC780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7f40d5b42e2761665471f1f5dc4eec81
2019-07-11 16:49:20,989 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:49:24,142 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DB79780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d61fe8b69d0014943479d7e32c7c2206
2019-07-11 16:49:25,152 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DFAEA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d61fe8b69d0014943479d7e32c7c2206
2019-07-11 16:49:26,157 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DFAEF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d61fe8b69d0014943479d7e32c7c2206
2019-07-11 16:50:26,075 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:50:46,797 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:51:19,123 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 16:51:26,808 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:51:36,842 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:51:39,808 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 16:51:47,130 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:51:50,714 - INFO - register_us.py[:239] - TuathaleDariuse198@nineboys.pro用户注册成功！
2019-07-11 16:51:57,165 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:51:57,250 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:52:01,428 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2924744E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4656de4cf95d22e6e5ca4709d3e49835
2019-07-11 16:52:02,437 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292474748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4656de4cf95d22e6e5ca4709d3e49835
2019-07-11 16:52:03,435 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292474358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4656de4cf95d22e6e5ca4709d3e49835
2019-07-11 16:52:10,581 - INFO - register_us.py[:239] - QuigleyeQuinlana213@nineboys.pro用户注册成功！
2019-07-11 16:52:13,305 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:52:16,473 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DB79B38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cbef12e472ce97a654a6f9f2d3f89b7c
2019-07-11 16:52:17,474 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DB54978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cbef12e472ce97a654a6f9f2d3f89b7c
2019-07-11 16:52:18,479 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DBA0630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cbef12e472ce97a654a6f9f2d3f89b7c
2019-07-11 16:53:14,786 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 16:53:42,617 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 16:53:55,013 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 16:54:01,638 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 16:54:11,674 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 16:54:24,299 - INFO - register_us.py[:239] - HuelaaObothc958@nineboys.org用户注册成功！
2019-07-11 16:54:39,368 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 16:54:42,501 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292032198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a637df3dec5c012c1e67f1a357224636
2019-07-11 16:54:43,516 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C291FFC8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a637df3dec5c012c1e67f1a357224636
2019-07-11 16:54:44,531 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C291FFC7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a637df3dec5c012c1e67f1a357224636
2019-07-11 16:55:11,116 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 16:56:54,159 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 16:57:50,881 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 16:59:17,057 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 17:00:04,257 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 17:01:21,423 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 17:01:31,456 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 17:02:03,701 - INFO - register_us.py[:239] - CletusaRaea415@nineboys.info用户注册成功！
2019-07-11 17:02:05,378 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 17:02:09,550 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DFB9C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/813a4d63dfb78587e386cc161c58cfbd
2019-07-11 17:02:10,552 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DB79208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/813a4d63dfb78587e386cc161c58cfbd
2019-07-11 17:02:11,561 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C38DB791D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/813a4d63dfb78587e386cc161c58cfbd
2019-07-11 17:02:15,917 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 17:02:26,045 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 17:02:58,644 - INFO - register_us.py[:239] - LouieeFrannee967@nineboys.info用户注册成功！
2019-07-11 17:03:00,503 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 17:03:03,872 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2924742E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7ab9c0b0db4ae0795ce6107dcd3a4657
2019-07-11 17:03:04,887 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292474F28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7ab9c0b0db4ae0795ce6107dcd3a4657
2019-07-11 17:03:05,894 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292474470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7ab9c0b0db4ae0795ce6107dcd3a4657
2019-07-11 17:06:56,693 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 17:09:13,388 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 17:12:49,603 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 17:13:39,715 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 17:13:49,747 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 17:18:49,808 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 17:21:38,074 - INFO - register_us.py[:350] - 任务系统出错，程序[sleep 10m]...
2019-07-11 17:34:21,771 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 17:35:34,336 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 17:36:26,249 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 17:36:36,282 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 17:36:52,112 - INFO - register_us.py[:239] - SladeeToddc758@nineboys.top用户注册成功！
2019-07-11 17:37:03,738 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 17:37:06,912 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292032668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0164bf932841cc55e054e6d6f17cf25e
2019-07-11 17:37:07,943 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292474518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0164bf932841cc55e054e6d6f17cf25e
2019-07-11 17:37:08,976 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29245E198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0164bf932841cc55e054e6d6f17cf25e
2019-07-11 17:38:28,898 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 17:39:32,884 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 17:39:41,308 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 17:39:51,333 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 17:40:05,439 - INFO - register_us.py[:239] - TadeocRudolphc986@nineboys.tech用户注册成功！
2019-07-11 17:40:07,672 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 17:40:11,830 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292032748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0646730f8e97e5cb7213e63a22f6246f
2019-07-11 17:40:12,830 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292250550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0646730f8e97e5cb7213e63a22f6246f
2019-07-11 17:40:13,831 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292250A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0646730f8e97e5cb7213e63a22f6246f
2019-07-11 17:44:02,466 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 17:49:30,500 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 17:51:19,002 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 17:52:22,810 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 17:52:31,562 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 17:52:41,594 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 17:52:57,601 - INFO - register_us.py[:239] - GeorgeaaClarae578@nineboys.ltd用户注册成功！
2019-07-11 17:53:00,092 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 17:53:04,254 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29246D828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9af4cf425d3c0d2ab6cd2f3e78e6820f
2019-07-11 17:53:05,262 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292474F98>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9af4cf425d3c0d2ab6cd2f3e78e6820f
2019-07-11 17:53:06,264 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292474780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9af4cf425d3c0d2ab6cd2f3e78e6820f
2019-07-11 17:56:36,415 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 18:00:39,963 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 18:02:34,108 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 18:05:51,443 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 18:08:10,476 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 18:08:20,523 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 18:08:56,794 - INFO - register_us.py[:239] - JenniecBrama159@nineboys.group用户注册成功！
2019-07-11 18:08:59,075 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 18:09:02,212 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29228BC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/04f7bbbb886175db6c13b7d7cea89fe7
2019-07-11 18:09:03,219 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29246D0B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/04f7bbbb886175db6c13b7d7cea89fe7
2019-07-11 18:09:04,224 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29246DA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/04f7bbbb886175db6c13b7d7cea89fe7
2019-07-11 18:13:17,275 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 18:16:34,258 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 18:16:44,328 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 18:17:32,230 - INFO - register_us.py[:239] - YvelyneeGabriela027@nineboys.xyz用户注册成功！
2019-07-11 18:17:35,002 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 18:17:38,197 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292250358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5e66d558b05b84fce6a3e8059a3394b5
2019-07-11 18:17:39,198 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29245E748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5e66d558b05b84fce6a3e8059a3394b5
2019-07-11 18:17:40,202 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29245E4A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5e66d558b05b84fce6a3e8059a3394b5
2019-07-11 18:19:24,920 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 18:21:17,023 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 18:23:38,121 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 18:23:48,160 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 18:24:00,763 - INFO - register_us.py[:239] - UdallcWesse286@nineboys.cn用户注册成功！
2019-07-11 18:24:04,840 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 18:24:10,515 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29245EEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/13c65ce01b23b3980a02dae4a4ace3cc
2019-07-11 18:24:11,590 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29245ED68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/13c65ce01b23b3980a02dae4a4ace3cc
2019-07-11 18:24:12,714 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29245E390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/13c65ce01b23b3980a02dae4a4ace3cc
2019-07-11 18:26:00,817 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 18:27:09,785 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 18:27:18,331 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 18:27:28,384 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 18:27:42,023 - INFO - register_us.py[:239] - AldenaMarielc421@nineboys.club用户注册成功！
2019-07-11 18:27:52,547 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 18:27:56,293 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29246D198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/34b2c074e7ef3b18e46ba18956704964
2019-07-11 18:27:57,302 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29201A8D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/34b2c074e7ef3b18e46ba18956704964
2019-07-11 18:27:58,307 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29201A320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/34b2c074e7ef3b18e46ba18956704964
2019-07-11 18:28:52,298 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 18:32:18,146 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 18:39:42,464 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 18:39:52,474 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 18:40:21,782 - INFO - register_us.py[:239] - VestacEdiee830@nineboys.fun用户注册成功！
2019-07-11 18:40:32,708 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 18:40:37,762 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29203C940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/126492a9778be270f24933e468c7f4ad
2019-07-11 18:40:38,842 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29201A6D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/126492a9778be270f24933e468c7f4ad
2019-07-11 18:40:39,939 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292250898>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/126492a9778be270f24933e468c7f4ad
2019-07-11 18:42:15,681 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 18:43:36,645 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 18:43:46,026 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 18:43:56,063 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 18:44:19,927 - INFO - register_us.py[:239] - NormaeOgelsvyc529@nineboy.club用户注册成功！
2019-07-11 18:44:26,342 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 18:44:31,177 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29201A860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ccf7a5a03fed481f5d76b0babfdaf23e
2019-07-11 18:44:32,188 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292032358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ccf7a5a03fed481f5d76b0babfdaf23e
2019-07-11 18:44:33,188 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2920323C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ccf7a5a03fed481f5d76b0babfdaf23e
2019-07-11 18:48:14,076 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 18:50:31,152 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 18:53:12,905 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 18:54:19,827 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 18:55:08,932 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 18:55:16,855 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 18:55:26,883 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 18:55:41,730 - INFO - register_us.py[:239] - NaricMindye438@nineboy.co用户注册成功！
2019-07-11 18:55:44,092 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 18:55:48,376 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292474E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cd4b9d0925a78899d4cfefeb9ea02bd5
2019-07-11 18:55:49,378 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292032278>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cd4b9d0925a78899d4cfefeb9ea02bd5
2019-07-11 18:55:50,381 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2920327F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/cd4b9d0925a78899d4cfefeb9ea02bd5
2019-07-11 18:58:23,017 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 19:00:06,297 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 19:00:16,328 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 19:00:29,298 - INFO - register_us.py[:239] - FlanePyroe931@nineboy.store用户注册成功！
2019-07-11 19:00:35,602 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 19:00:38,779 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244D908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/696430ce3ffafce57f4e3f69dcb4ed18
2019-07-11 19:00:39,780 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292257DD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/696430ce3ffafce57f4e3f69dcb4ed18
2019-07-11 19:00:40,781 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29228B1D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/696430ce3ffafce57f4e3f69dcb4ed18
2019-07-11 19:02:16,517 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 19:03:22,706 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 19:04:11,291 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 19:04:21,324 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 19:04:35,254 - INFO - register_us.py[:239] - CapriceaLaele350@nineboy.group用户注册成功！
2019-07-11 19:04:38,739 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 19:04:41,898 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922572B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/408df78484aa822daf4294e6b63bd199
2019-07-11 19:04:42,899 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A2438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/408df78484aa822daf4294e6b63bd199
2019-07-11 19:04:43,901 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292257B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/408df78484aa822daf4294e6b63bd199
2019-07-11 19:05:53,278 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 19:08:54,544 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 19:09:00,836 - INFO - register_us.py[:347] - 当前无注册任务，程序[sleep 10m]...
2019-07-11 19:19:09,217 - INFO - register_us.py[:347] - 当前无注册任务，程序[sleep 10m]...
2019-07-11 19:30:56,993 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-11 19:32:05,861 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 19:34:46,035 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 19:37:36,912 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 19:39:15,438 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 19:40:30,578 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 19:40:40,612 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 19:40:57,232 - INFO - register_us.py[:239] - IdaeYuria206@nineboy.ltd用户注册成功！
2019-07-11 19:41:01,490 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 19:41:04,853 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292257F60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4d8baa88fa17b1c72a12930442afbdbc
2019-07-11 19:41:05,854 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A8E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4d8baa88fa17b1c72a12930442afbdbc
2019-07-11 19:41:06,858 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A2D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4d8baa88fa17b1c72a12930442afbdbc
2019-07-11 19:42:59,875 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 19:44:34,156 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 19:45:48,484 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 19:45:58,516 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 19:46:15,395 - INFO - register_us.py[:239] - LangaBritte105@nineboy.art用户注册成功！
2019-07-11 19:46:17,788 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 19:46:20,938 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A20F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee4b6c35a0a9bebfcdde2b86723a0082
2019-07-11 19:46:21,940 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A2BA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee4b6c35a0a9bebfcdde2b86723a0082
2019-07-11 19:46:22,941 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A2048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee4b6c35a0a9bebfcdde2b86723a0082
2019-07-11 19:50:01,948 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 19:51:21,118 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 19:52:29,353 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 19:52:39,382 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 19:52:53,746 - INFO - register_us.py[:239] - ArvidaEliciac650@geabest.club用户注册成功！
2019-07-11 19:52:56,727 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 19:53:00,883 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29203C048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/348f3a15a5763f6a0fdc7a7d1520073f
2019-07-11 19:53:01,898 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29228BEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/348f3a15a5763f6a0fdc7a7d1520073f
2019-07-11 19:53:02,914 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29229D198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/348f3a15a5763f6a0fdc7a7d1520073f
2019-07-11 19:56:17,959 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 19:57:31,514 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 19:58:28,394 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 19:58:38,424 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 19:58:52,320 - INFO - register_us.py[:239] - JinnyaZillie209@geabest.ltd用户注册成功！
2019-07-11 19:59:00,015 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 19:59:03,198 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922B6C18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/acee89d402d4b2b3700344080b05815c
2019-07-11 19:59:04,195 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922B6518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/acee89d402d4b2b3700344080b05815c
2019-07-11 19:59:05,197 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244D518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/acee89d402d4b2b3700344080b05815c
2019-07-11 20:00:25,954 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 20:00:36,299 - INFO - register_us.py[:347] - 当前无注册任务，程序[sleep 10m]...
2019-07-11 20:12:34,897 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 20:12:53,248 - INFO - register_us.py[:347] - 当前无注册任务，程序[sleep 10m]...
2019-07-11 20:24:01,875 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 20:29:16,309 - INFO - register_us.py[:146] - 注册出错，程序结束！
2019-07-11 20:30:40,385 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 20:31:29,836 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 20:31:39,867 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 20:31:52,464 - INFO - register_us.py[:239] - KiraleYuria305@geabest.info用户注册成功！
2019-07-11 20:32:30,038 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 20:32:33,195 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A8EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d585db2b8bab9caddf8ca1dd17fb2fb9
2019-07-11 20:32:34,203 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244D7F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d585db2b8bab9caddf8ca1dd17fb2fb9
2019-07-11 20:32:35,219 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244DF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d585db2b8bab9caddf8ca1dd17fb2fb9
2019-07-11 20:33:45,566 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 20:33:54,625 - INFO - register_us.py[:347] - 当前无注册任务，程序[sleep 10m]...
2019-07-11 20:45:56,103 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 20:46:58,355 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 20:47:08,390 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 20:47:21,530 - INFO - register_us.py[:239] - CorinneaTyreesee982@geabest.pro用户注册成功！
2019-07-11 20:48:11,143 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 20:48:14,478 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244D6D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bab63742275fa67a67b114c55eac4f32
2019-07-11 20:48:15,483 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A88D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bab63742275fa67a67b114c55eac4f32
2019-07-11 20:48:16,492 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A85F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bab63742275fa67a67b114c55eac4f32
2019-07-11 20:49:49,596 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 20:50:36,152 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 20:50:43,967 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 20:50:53,997 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 20:51:06,435 - INFO - register_us.py[:239] - WallacecAbrahamc925@geabest.mobi用户注册成功！
2019-07-11 20:51:09,294 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 20:51:13,498 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244D2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/18eea0b55f199ea38fdac51614115fd1
2019-07-11 20:51:14,500 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244DA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/18eea0b55f199ea38fdac51614115fd1
2019-07-11 20:51:15,507 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244D0B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/18eea0b55f199ea38fdac51614115fd1
2019-07-11 20:52:33,467 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 20:54:11,129 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 20:54:21,161 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 20:54:38,095 - INFO - register_us.py[:239] - PenleyeMaggiea709@geabest.com.cn用户注册成功！
2019-07-11 20:54:52,681 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 20:54:56,888 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922B6BA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4d662a9a39e0170b85f3df868b915996
2019-07-11 20:54:57,893 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29246D048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4d662a9a39e0170b85f3df868b915996
2019-07-11 20:54:58,909 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29246DCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/4d662a9a39e0170b85f3df868b915996
2019-07-11 20:56:21,514 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 20:57:10,318 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 20:57:18,839 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 20:57:28,867 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 20:57:58,128 - INFO - register_us.py[:239] - JettiecPoncec970@geabest.cc用户注册成功！
2019-07-11 20:58:14,863 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 20:58:19,016 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A2BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fb7449727065a1648023bc5818ba2104
2019-07-11 20:58:20,022 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922B6470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fb7449727065a1648023bc5818ba2104
2019-07-11 20:58:21,021 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922B6240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fb7449727065a1648023bc5818ba2104
2019-07-11 21:00:15,503 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 21:01:22,390 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 21:01:32,420 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 21:01:47,205 - INFO - register_us.py[:239] - NieshaaYettae971@geabest.online用户注册成功！
2019-07-11 21:02:26,725 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 21:02:29,914 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922A2550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3278cd1c9a40909c81558c1bc2acc6d6
2019-07-11 21:02:30,916 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922B6E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3278cd1c9a40909c81558c1bc2acc6d6
2019-07-11 21:02:31,925 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922B6518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3278cd1c9a40909c81558c1bc2acc6d6
2019-07-11 21:04:00,764 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-11 21:10:45,684 - INFO - register_us.py[:150] - 等待超时，程序终止！
2019-07-11 21:14:47,089 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-11 21:17:14,642 - INFO - register_us.py[:126] - 注册出错，程序结束！
2019-07-11 21:19:05,870 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 21:20:08,975 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 21:20:19,006 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 21:20:49,192 - INFO - register_us.py[:239] - KalindaaHurleyc198@geabest.vip用户注册成功！
2019-07-11 21:21:05,286 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 21:21:09,522 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922570B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6ee17607da681704028a5d0c9f6142e5
2019-07-11 21:21:10,526 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244DB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6ee17607da681704028a5d0c9f6142e5
2019-07-11 21:21:11,524 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244D518>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6ee17607da681704028a5d0c9f6142e5
2019-07-11 21:24:11,162 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 21:26:01,491 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 21:26:11,535 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 21:26:48,898 - INFO - register_us.py[:239] - TacyeSaulc084@geabest.store用户注册成功！
2019-07-11 21:26:57,035 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 21:27:01,193 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29201A6D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9ae342421afee9692e279a6551ef19f1
2019-07-11 21:27:02,209 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29201A390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9ae342421afee9692e279a6551ef19f1
2019-07-11 21:27:03,210 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29201A710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9ae342421afee9692e279a6551ef19f1
2019-07-11 21:29:50,697 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 21:31:50,029 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 21:32:00,047 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 21:32:43,929 - INFO - register_us.py[:239] - JosiaheNanic698@yyw.ltd用户注册成功！
2019-07-11 21:32:45,101 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 21:32:49,268 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292257CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3b5097a612451332c20749d1962e4092
2019-07-11 21:32:50,284 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C2922570B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3b5097a612451332c20749d1962e4092
2019-07-11 21:32:51,300 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292257A20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3b5097a612451332c20749d1962e4092
2019-07-11 21:34:31,374 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 21:35:22,802 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 21:35:30,098 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 21:35:40,131 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 21:35:53,032 - INFO - register_us.py[:239] - IteeKarane714@gets.vip用户注册成功！
2019-07-11 21:35:56,238 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 21:35:59,380 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29246DA20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/686e56d259f83c0cc1a3d90ee7ba32c4
2019-07-11 21:36:00,381 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29246DDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/686e56d259f83c0cc1a3d90ee7ba32c4
2019-07-11 21:36:01,382 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29246DD68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/686e56d259f83c0cc1a3d90ee7ba32c4
2019-07-11 21:37:18,075 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 21:38:02,316 - INFO - register_us.py[:217] - 从接口获取的StateOrRegion信息对应不上，默认为下拉列表的第一个州或地区！
2019-07-11 21:38:07,977 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 21:38:18,026 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 21:38:31,334 - INFO - register_us.py[:239] - NeseeBinga403@gets.fun用户注册成功！
2019-07-11 21:39:09,593 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 21:39:12,766 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292257208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/723f5d4ce71c9612077c3f101f1a98fb
2019-07-11 21:39:13,782 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292257CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/723f5d4ce71c9612077c3f101f1a98fb
2019-07-11 21:39:14,814 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C292257A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/723f5d4ce71c9612077c3f101f1a98fb
2019-07-11 21:40:46,310 - INFO - register_us.py[:156] - 正在设置用户的基本信息...
2019-07-11 21:41:37,489 - INFO - register_us.py[:233] - 点击提交个人信息的设置!
2019-07-11 21:41:47,534 - INFO - register_us.py[:117] - 个人信息设置成功！success!
2019-07-11 21:42:00,223 - INFO - register_us.py[:239] - UldwynacQahiraa730@yyw.wiki用户注册成功！
2019-07-11 21:42:54,841 - INFO - register_us.py[:273] - 注册信息已成功入库！
2019-07-11 21:42:57,999 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29228B358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee5a28d18d16ce04f2436b6fa5d12331
2019-07-11 21:42:59,015 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000000C29244DA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ee5a28d18d16ce04f2436b6fa5d12331
