2019-07-04 02:09:57,221 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ccd220fc6c6dec2bb1981486e1c62b4e
2019-07-04 02:09:58,223 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ccd220fc6c6dec2bb1981486e1c62b4e
2019-07-04 02:09:59,219 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ccd220fc6c6dec2bb1981486e1c62b4e
2019-07-04 02:12:42,485 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 02:15:58,830 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 02:29:20,646 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 02:42:24,059 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 02:45:18,341 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 02:45:28,383 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 02:45:45,831 - INFO - register_de.py[:223] - YuleaCristinaa307@zaful.biz用户注册成功！
2019-07-04 02:47:30,404 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/be3b69f4d19ed3b745576b2b28b7a7a9
2019-07-04 02:47:31,435 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/be3b69f4d19ed3b745576b2b28b7a7a9
2019-07-04 02:47:32,467 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077147756D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/be3b69f4d19ed3b745576b2b28b7a7a9
2019-07-04 02:51:01,426 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 02:52:33,482 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 02:55:30,008 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 03:08:37,014 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 03:23:18,956 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 03:25:29,918 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 03:38:45,654 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 03:50:08,909 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 03:51:01,557 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 03:51:11,590 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 03:51:30,720 - INFO - register_de.py[:223] - EmileeaOnawae675@zaful.xyz用户注册成功！
2019-07-04 03:51:35,831 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 03:51:40,090 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA15F8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/89b560a336161205f0c1405bc7fec3f4
2019-07-04 03:51:41,094 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/89b560a336161205f0c1405bc7fec3f4
2019-07-04 03:51:42,104 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5ABE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/89b560a336161205f0c1405bc7fec3f4
2019-07-04 03:53:09,420 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 03:53:56,126 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 03:54:06,201 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 03:54:25,830 - INFO - register_de.py[:223] - LorenaDolphe976@zaful.net.cn用户注册成功！
2019-07-04 03:56:02,974 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938C18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/83b9e4d596a81f0bf0d1dd165872bfdb
2019-07-04 03:56:03,976 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5ACF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/83b9e4d596a81f0bf0d1dd165872bfdb
2019-07-04 03:56:04,977 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AEB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/83b9e4d596a81f0bf0d1dd165872bfdb
2019-07-04 03:58:57,841 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 04:09:01,658 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 04:20:59,742 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 04:32:03,328 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 04:45:37,769 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 04:57:04,065 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 05:08:26,574 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 05:21:01,015 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 05:31:11,842 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 05:44:18,834 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 05:54:35,650 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:04:40,957 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:15:17,854 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:25:22,192 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:35:42,044 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:46:02,313 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 06:56:05,733 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:07:02,244 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:17:05,286 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:27:27,387 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:37:49,268 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:48:08,665 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 07:58:28,249 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 08:08:33,076 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 08:18:37,170 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 08:30:54,646 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 08:41:01,850 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 08:51:05,082 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 09:04:08,671 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 09:14:14,296 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 09:24:17,624 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 09:34:24,483 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 09:44:28,483 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 09:55:39,838 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:05:42,704 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:15:45,747 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:25:50,555 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:36:02,099 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:46:06,049 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 10:56:10,017 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:06:12,719 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:16:15,388 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:26:19,615 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:36:37,358 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:46:41,281 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 11:56:45,285 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:06:50,957 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:16:54,534 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:26:57,940 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:37:00,297 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:47:02,797 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 12:57:08,453 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:07:13,186 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:17:16,013 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:27:19,278 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:37:23,262 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:47:26,574 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 13:57:30,964 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:07:37,418 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:17:41,510 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:27:44,275 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:37:51,666 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:47:57,276 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 14:58:08,716 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:08:11,996 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:18:20,153 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:28:44,005 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:38:47,816 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:48:56,739 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 15:58:59,441 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 16:10:20,476 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:11:07,590 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:11:17,622 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:11:31,966 - INFO - register_de.py[:223] - LalitacNorberte953@zaful.work用户注册成功！
2019-07-04 16:11:32,926 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:11:36,053 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C794E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5e4c689c4936a815c4490f2fad2f3dd9
2019-07-04 16:11:37,053 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CFB70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5e4c689c4936a815c4490f2fad2f3dd9
2019-07-04 16:11:38,053 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CFE10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5e4c689c4936a815c4490f2fad2f3dd9
2019-07-04 16:13:24,101 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:14:19,765 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:14:29,803 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:14:50,035 - INFO - register_de.py[:223] - AntoineaPhilisc481@zaful.fun用户注册成功！
2019-07-04 16:14:51,740 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:14:55,899 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ecbec6d29f7bb6571ce539facf225e32
2019-07-04 16:14:56,915 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ecbec6d29f7bb6571ce539facf225e32
2019-07-04 16:14:57,931 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ecbec6d29f7bb6571ce539facf225e32
2019-07-04 16:17:21,038 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 16:18:41,530 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:19:26,571 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:19:36,602 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:19:50,958 - INFO - register_de.py[:223] - IzaiahaCalliopea108@ninebot.tv用户注册成功！
2019-07-04 16:19:53,991 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:19:58,149 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7a80b09636271cf04a551f1e14886115
2019-07-04 16:19:59,165 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC438>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7a80b09636271cf04a551f1e14886115
2019-07-04 16:20:00,197 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160ACA90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7a80b09636271cf04a551f1e14886115
2019-07-04 16:21:31,218 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:22:28,440 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:22:38,474 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:22:59,011 - INFO - register_de.py[:223] - WaltacTacitae615@ninebot.ltd用户注册成功！
2019-07-04 16:22:59,883 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:23:03,024 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CFF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a80ffa9e43343172114060a511d71574
2019-07-04 16:23:04,056 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC278>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a80ffa9e43343172114060a511d71574
2019-07-04 16:23:05,072 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC048>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a80ffa9e43343172114060a511d71574
2019-07-04 16:24:20,968 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:25:06,749 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:25:16,794 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:25:35,990 - INFO - register_de.py[:223] - ChandrikacRanita912@nineboy.com.cn用户注册成功！
2019-07-04 16:25:40,731 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:25:44,890 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CF908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7aaf7b532321552abed486b12f82e4da
2019-07-04 16:25:45,891 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7aaf7b532321552abed486b12f82e4da
2019-07-04 16:25:46,892 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/7aaf7b532321552abed486b12f82e4da
2019-07-04 16:27:05,366 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:27:53,547 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:28:03,563 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:28:22,565 - INFO - register_de.py[:223] - ChandrikacFontellac085@nineboy.top用户注册成功！
2019-07-04 16:28:23,494 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:28:26,632 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91A58>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e9125add0fabb1dbe99a444791bd67e
2019-07-04 16:28:27,631 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C53908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e9125add0fabb1dbe99a444791bd67e
2019-07-04 16:28:28,632 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C53828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/6e9125add0fabb1dbe99a444791bd67e
2019-07-04 16:30:08,072 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:31:00,946 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:31:10,976 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:31:30,709 - INFO - register_de.py[:223] - BessieeWaltone280@nineboy.pro用户注册成功！
2019-07-04 16:31:32,880 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:31:37,082 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f8ae62499d3bb6d8da10f151bc1065ec
2019-07-04 16:31:38,089 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C910F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f8ae62499d3bb6d8da10f151bc1065ec
2019-07-04 16:31:39,114 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/f8ae62499d3bb6d8da10f151bc1065ec
2019-07-04 16:34:03,920 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 16:35:50,989 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:37:19,143 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:37:29,178 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:38:28,849 - INFO - register_de.py[:223] - RosalbaaCeliaa078@nineboy.site用户注册成功！
2019-07-04 16:38:30,971 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:38:34,094 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/94fe68ce05b07d233ef9f12a5a059d6b
2019-07-04 16:38:35,098 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716988A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/94fe68ce05b07d233ef9f12a5a059d6b
2019-07-04 16:38:36,103 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716988BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/94fe68ce05b07d233ef9f12a5a059d6b
2019-07-04 16:40:21,723 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 16:41:36,716 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:42:15,091 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:42:25,138 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:42:41,135 - INFO - register_de.py[:223] - JaninaeVivienc204@nineboy.vip用户注册成功！
2019-07-04 16:42:42,865 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:42:45,991 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1a484f53ebb55a6b276193e845f5fcc8
2019-07-04 16:42:46,992 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AEB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1a484f53ebb55a6b276193e845f5fcc8
2019-07-04 16:42:48,008 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5ADD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1a484f53ebb55a6b276193e845f5fcc8
2019-07-04 16:44:04,669 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:44:56,238 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:45:06,266 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:45:24,153 - INFO - register_de.py[:223] - NormandcDaltone095@nineboy.biz用户注册成功！
2019-07-04 16:45:25,348 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:45:29,509 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/976204eb721fd7e0e75a09e136795a8f
2019-07-04 16:45:30,508 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169885C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/976204eb721fd7e0e75a09e136795a8f
2019-07-04 16:45:31,506 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716988DD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/976204eb721fd7e0e75a09e136795a8f
2019-07-04 16:46:48,699 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:47:36,127 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:47:46,186 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:48:04,876 - INFO - register_de.py[:223] - ValarieaSethe529@nineboy.net用户注册成功！
2019-07-04 16:48:06,679 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:48:09,797 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d92b185d56b891157d7c9255b0402aa5
2019-07-04 16:48:10,806 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d92b185d56b891157d7c9255b0402aa5
2019-07-04 16:48:11,809 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938B38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d92b185d56b891157d7c9255b0402aa5
2019-07-04 16:51:26,590 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 16:53:37,900 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:55:09,678 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:55:19,716 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:55:33,814 - INFO - register_de.py[:223] - ArchieeWindyc468@nineboy.cc用户注册成功！
2019-07-04 16:55:41,205 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:55:44,392 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716988B70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eb2e1d43e4714435022ef9236a4a3211
2019-07-04 16:55:45,405 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169376A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eb2e1d43e4714435022ef9236a4a3211
2019-07-04 16:55:46,410 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eb2e1d43e4714435022ef9236a4a3211
2019-07-04 16:57:08,492 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 16:57:53,347 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 16:58:03,398 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 16:58:22,112 - INFO - register_de.py[:223] - KihoeCalac794@aukey.online用户注册成功！
2019-07-04 16:58:24,188 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 16:58:28,313 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AC18>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/34cac65f08e7be7c086113ecc97ec2f7
2019-07-04 16:58:29,323 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716988828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/34cac65f08e7be7c086113ecc97ec2f7
2019-07-04 16:58:30,327 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BD978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/34cac65f08e7be7c086113ecc97ec2f7
2019-07-04 16:59:49,392 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 17:00:36,665 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 17:00:46,714 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 17:01:05,201 - INFO - register_de.py[:223] - MillyaKerrinc814@aukey.live用户注册成功！
2019-07-04 17:01:06,194 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 17:01:09,341 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bfa913501b7bdd7389b229375cb28320
2019-07-04 17:01:10,356 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bfa913501b7bdd7389b229375cb28320
2019-07-04 17:01:11,373 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937CC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bfa913501b7bdd7389b229375cb28320
2019-07-04 17:03:16,531 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 17:04:26,998 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 17:04:37,016 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 17:05:30,990 - INFO - register_de.py[:223] - HillelcNadac985@aukey.fun用户注册成功！
2019-07-04 17:05:34,478 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 17:05:37,611 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C910F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/724d0dd1936bd519c119cc5925146153
2019-07-04 17:05:38,611 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169374A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/724d0dd1936bd519c119cc5925146153
2019-07-04 17:05:39,626 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937D68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/724d0dd1936bd519c119cc5925146153
2019-07-04 17:06:57,964 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 17:07:47,892 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 17:07:57,957 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 17:08:37,918 - INFO - register_de.py[:223] - DallaseFitzhughc342@aukey.ltd用户注册成功！
2019-07-04 17:08:39,256 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 17:08:42,415 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1B00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fab58bf403d2d5a5f75d96b435e97486
2019-07-04 17:08:43,430 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716988588>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fab58bf403d2d5a5f75d96b435e97486
2019-07-04 17:08:44,431 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716988080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/fab58bf403d2d5a5f75d96b435e97486
2019-07-04 17:11:03,094 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 17:12:27,406 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 17:13:17,566 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 17:13:27,592 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 17:13:47,363 - INFO - register_de.py[:223] - AdleraNicke237@aukey.net.cn用户注册成功！
2019-07-04 17:13:48,664 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 17:13:52,946 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169888D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e2eba4f45fe3b1edaa54b8690bbc89bd
2019-07-04 17:13:53,953 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AAC8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e2eba4f45fe3b1edaa54b8690bbc89bd
2019-07-04 17:13:54,951 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169889B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e2eba4f45fe3b1edaa54b8690bbc89bd
2019-07-04 17:15:06,930 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 17:15:55,798 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 17:16:05,831 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 17:16:20,045 - INFO - register_de.py[:223] - PippaaNicolazae376@aukey.mobi用户注册成功！
2019-07-04 17:16:21,333 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 17:16:24,518 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d287077da240148ac5b942a8fa6c6e6a
2019-07-04 17:16:25,516 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d287077da240148ac5b942a8fa6c6e6a
2019-07-04 17:16:26,517 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C917B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/d287077da240148ac5b942a8fa6c6e6a
2019-07-04 17:18:49,819 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 17:20:28,875 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 17:20:38,923 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 17:21:38,166 - INFO - register_de.py[:223] - EfremeNaomiae394@nineboys.co用户注册成功！
2019-07-04 17:21:44,540 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 17:21:48,672 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c796c3bbffcb8d93dd0a51c1d12f974b
2019-07-04 17:21:49,687 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c796c3bbffcb8d93dd0a51c1d12f974b
2019-07-04 17:21:50,686 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDCF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c796c3bbffcb8d93dd0a51c1d12f974b
2019-07-04 17:23:59,456 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 17:36:44,534 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 17:49:38,979 - INFO - register_de.py[:333] - 任务系统出错，程序[sleep 10m]...
2019-07-04 18:00:53,019 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 18:01:40,032 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 18:01:50,082 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 18:02:08,377 - INFO - register_de.py[:223] - BenaaValterrac942@nineboys.art用户注册成功！
2019-07-04 18:02:09,208 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 18:02:13,352 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169886A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0a3ce023293b47164fab9ef0d5460baa
2019-07-04 18:02:14,352 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0a3ce023293b47164fab9ef0d5460baa
2019-07-04 18:02:15,352 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0a3ce023293b47164fab9ef0d5460baa
2019-07-04 18:03:30,513 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 18:04:19,665 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 18:04:24,324 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 18:16:24,061 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 18:20:07,310 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 18:20:17,354 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 18:20:57,752 - INFO - register_de.py[:223] - VilaeFarona875@nineboys.info用户注册成功！
2019-07-04 18:20:59,038 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 18:21:02,200 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169884E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/623ebb82b4080fdf0e52ee0908a3833c
2019-07-04 18:21:03,197 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937DD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/623ebb82b4080fdf0e52ee0908a3833c
2019-07-04 18:21:04,200 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/623ebb82b4080fdf0e52ee0908a3833c
2019-07-04 18:21:07,333 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 18:32:29,733 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 18:34:56,135 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 18:36:14,754 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 18:37:02,270 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 18:37:12,312 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 18:37:26,837 - INFO - register_de.py[:223] - HeveanaSkylere056@nineboys.xyz用户注册成功！
2019-07-04 18:37:28,853 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 18:37:31,964 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169380F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e180e76598207a16c8f6c86566ce6dd3
2019-07-04 18:37:32,978 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91DD8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e180e76598207a16c8f6c86566ce6dd3
2019-07-04 18:37:33,988 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91CF8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e180e76598207a16c8f6c86566ce6dd3
2019-07-04 18:37:38,416 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 18:47:42,397 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 18:57:45,595 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 19:07:48,915 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 19:17:53,072 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 19:27:59,230 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 19:38:10,794 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 19:48:14,363 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 19:58:19,713 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 20:08:23,911 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 20:19:57,483 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 20:20:53,450 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 20:21:03,495 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 20:21:23,281 - INFO - register_de.py[:223] - AnseleZelmae689@yyw.link用户注册成功！
2019-07-04 20:21:24,733 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 20:21:29,505 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169374E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/20ff79fb0475b5000b591154f0bc592e
2019-07-04 20:21:30,520 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/20ff79fb0475b5000b591154f0bc592e
2019-07-04 20:21:31,526 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/20ff79fb0475b5000b591154f0bc592e
2019-07-04 20:23:14,883 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 20:24:01,844 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 20:24:11,871 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 20:24:29,501 - INFO - register_de.py[:223] - HaeleighaMariahc712@beads.ren用户注册成功！
2019-07-04 20:24:31,084 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 20:24:39,363 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CF780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3dcf586874c44831fe6e14f224995ee3
2019-07-04 20:24:40,457 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CF3C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3dcf586874c44831fe6e14f224995ee3
2019-07-04 20:24:41,460 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3dcf586874c44831fe6e14f224995ee3
2019-07-04 20:24:46,177 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 20:37:51,541 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 20:39:42,299 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 20:41:13,558 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 20:42:19,122 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 20:42:29,177 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 20:42:46,663 - INFO - register_de.py[:223] - LidiacTasidaa026@beads.group用户注册成功！
2019-07-04 20:42:49,438 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 20:42:53,692 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937D68>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1f058fe81b25d93e5949dd9f3defdd15
2019-07-04 20:42:54,701 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937320>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1f058fe81b25d93e5949dd9f3defdd15
2019-07-04 20:42:55,698 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1f058fe81b25d93e5949dd9f3defdd15
2019-07-04 20:44:57,380 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 20:45:51,526 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 20:46:01,559 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 20:46:39,193 - INFO - register_de.py[:223] - LenaaAustinc270@beads.pub用户注册成功！
2019-07-04 20:46:40,687 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 20:46:43,946 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91978>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8e8c7303e5fa127962b0196b85bfb5dc
2019-07-04 20:46:44,946 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA19E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8e8c7303e5fa127962b0196b85bfb5dc
2019-07-04 20:46:45,946 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077147756D8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8e8c7303e5fa127962b0196b85bfb5dc
2019-07-04 20:48:41,465 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 20:50:12,800 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 20:51:06,352 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 20:51:16,389 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 20:51:31,191 - INFO - register_de.py[:223] - ZabbaiaYoshikoa523@beads.wang用户注册成功！
2019-07-04 20:51:32,728 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 20:51:36,854 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CFF28>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8fae7f4e066677e91ddf46ca980277c3
2019-07-04 20:51:37,856 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5AC88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8fae7f4e066677e91ddf46ca980277c3
2019-07-04 20:51:38,858 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5A710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/8fae7f4e066677e91ddf46ca980277c3
2019-07-04 20:54:25,016 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 20:55:45,576 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 20:56:34,665 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 20:56:44,699 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 20:57:02,842 - INFO - register_de.py[:223] - DancFreeda471@beads.link用户注册成功！
2019-07-04 20:57:04,133 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 20:57:07,978 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716988080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c752221dc473767537cd4410276dd7e8
2019-07-04 20:57:08,983 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160ACDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c752221dc473767537cd4410276dd7e8
2019-07-04 20:57:09,994 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC4E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/c752221dc473767537cd4410276dd7e8
2019-07-04 20:58:54,560 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 20:59:53,685 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 21:00:03,760 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 21:00:21,139 - INFO - register_de.py[:223] - NorwardaOdama746@beads.name用户注册成功！
2019-07-04 21:00:22,686 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 21:00:25,856 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDEB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ec66864d01e15f5e03201ffa49ebecac
2019-07-04 21:00:26,864 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169373C8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ec66864d01e15f5e03201ffa49ebecac
2019-07-04 21:00:27,874 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937208>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/ec66864d01e15f5e03201ffa49ebecac
2019-07-04 21:02:04,588 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 21:03:08,091 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 21:03:18,132 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 21:03:34,097 - INFO - register_de.py[:223] - AlonzoaHeywoode783@beads.kim用户注册成功！
2019-07-04 21:03:36,624 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 21:03:40,752 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/807cd633022f661f82661050c58d4283
2019-07-04 21:03:41,750 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA18D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/807cd633022f661f82661050c58d4283
2019-07-04 21:03:42,757 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA14E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/807cd633022f661f82661050c58d4283
2019-07-04 21:05:02,010 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 21:05:56,215 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 21:06:06,254 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 21:06:26,755 - INFO - register_de.py[:223] - WelsseDolanc054@beads.red用户注册成功！
2019-07-04 21:06:28,005 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 21:06:31,140 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C5ABE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e9ff1b9f1438ca40fa8a9b1517a96c21
2019-07-04 21:06:32,138 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e9ff1b9f1438ca40fa8a9b1517a96c21
2019-07-04 21:06:33,142 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169377B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/e9ff1b9f1438ca40fa8a9b1517a96c21
2019-07-04 21:08:11,943 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 21:09:49,161 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 21:09:59,199 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 21:10:40,437 - INFO - register_de.py[:223] - OctaviacLatimere579@anker.site用户注册成功！
2019-07-04 21:10:42,795 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 21:10:45,932 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91FD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a9804fb0fe2a15406ab3cc4b5f00ee7a
2019-07-04 21:10:46,946 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716938358>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a9804fb0fe2a15406ab3cc4b5f00ee7a
2019-07-04 21:10:47,950 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91E48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/a9804fb0fe2a15406ab3cc4b5f00ee7a
2019-07-04 21:12:27,602 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 21:18:05,327 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 21:23:31,397 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-04 21:25:04,332 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 21:26:01,525 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 21:26:11,561 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 21:26:31,738 - INFO - register_de.py[:223] - SapphirecPole809@shein.wang用户注册成功！
2019-07-04 21:26:36,935 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 21:26:41,204 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDE48>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/06dda8bfafd148f6b7b69e3e8d8e0f4c
2019-07-04 21:26:42,225 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDB00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/06dda8bfafd148f6b7b69e3e8d8e0f4c
2019-07-04 21:26:43,233 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/06dda8bfafd148f6b7b69e3e8d8e0f4c
2019-07-04 21:26:47,722 - INFO - register_de.py[:330] - 当前无注册任务，程序[sleep 10m]...
2019-07-04 21:39:18,586 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 21:41:28,171 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 21:41:38,201 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 21:42:29,516 - INFO - register_de.py[:223] - FinnegancKalindac904@shein.kim用户注册成功！
2019-07-04 21:42:30,356 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 21:42:34,519 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160ACB38>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9369203c12dd4051d2ce0b460cd46d8f
2019-07-04 21:42:35,523 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BD748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9369203c12dd4051d2ce0b460cd46d8f
2019-07-04 21:42:36,527 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716988198>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/9369203c12dd4051d2ce0b460cd46d8f
2019-07-04 21:43:56,549 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 21:46:11,261 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 21:47:46,755 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 21:49:15,513 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 21:50:52,843 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 21:51:40,793 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 21:51:50,844 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 21:52:10,037 - INFO - register_de.py[:223] - ElmorecLindac645@zaful.mobi用户注册成功！
2019-07-04 21:52:14,749 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 21:52:17,909 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/640c1933db23ab87ed65a5851f5c77ae
2019-07-04 21:52:18,920 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160ACEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/640c1933db23ab87ed65a5851f5c77ae
2019-07-04 21:52:19,922 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/640c1933db23ab87ed65a5851f5c77ae
2019-07-04 21:53:27,329 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 21:55:05,867 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 21:56:20,576 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 21:57:42,960 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 21:59:06,830 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 22:00:19,053 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 22:01:05,603 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 22:01:15,663 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 22:01:32,135 - INFO - register_de.py[:223] - AmityaOthniele832@zaful.xyz用户注册成功！
2019-07-04 22:01:34,440 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 22:01:38,594 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bb6dd016ccf82b9efc9e7e6fb0b8cc00
2019-07-04 22:01:39,613 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91AC8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bb6dd016ccf82b9efc9e7e6fb0b8cc00
2019-07-04 22:01:40,633 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/bb6dd016ccf82b9efc9e7e6fb0b8cc00
2019-07-04 22:03:01,659 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 22:05:51,656 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 22:08:40,484 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 22:13:56,430 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-04 22:16:25,719 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 22:17:40,312 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 22:17:50,361 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 22:18:17,453 - INFO - register_de.py[:223] - ReidcFlorencec237@zaful.net.cn用户注册成功！
2019-07-04 22:18:18,845 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 22:18:21,970 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160CF780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3f5f5ca6e52fcde668b736ec82e382c9
2019-07-04 22:18:22,968 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C790B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3f5f5ca6e52fcde668b736ec82e382c9
2019-07-04 22:18:23,971 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79710>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3f5f5ca6e52fcde668b736ec82e382c9
2019-07-04 22:19:43,600 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 22:21:57,723 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 22:23:14,165 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 22:24:26,625 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 22:25:46,979 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 22:26:37,211 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 22:26:47,247 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 22:27:05,160 - INFO - register_de.py[:223] - AnnabelcGaetanea517@zaful.work用户注册成功！
2019-07-04 22:27:10,183 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 22:27:14,350 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eee2e4645b2c9338f727359f83c8e212
2019-07-04 22:27:15,363 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937390>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eee2e4645b2c9338f727359f83c8e212
2019-07-04 22:27:16,381 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937F60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/eee2e4645b2c9338f727359f83c8e212
2019-07-04 22:32:30,519 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-04 22:34:45,118 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 22:37:20,333 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 22:39:05,011 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 22:40:09,024 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 22:40:19,066 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 22:40:38,055 - INFO - register_de.py[:223] - SullyaMyrac064@ninebot.tv用户注册成功！
2019-07-04 22:40:44,056 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 22:40:49,588 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BD908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5e8de6ade2f8e71af08b3c20c47b4bbd
2019-07-04 22:40:50,592 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79780>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5e8de6ade2f8e71af08b3c20c47b4bbd
2019-07-04 22:40:51,598 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C79080>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/5e8de6ade2f8e71af08b3c20c47b4bbd
2019-07-04 22:43:28,939 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 22:48:45,972 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-04 22:50:09,529 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 22:52:45,399 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 22:57:08,259 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 22:58:36,055 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 22:59:49,562 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 23:02:15,879 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 23:03:29,031 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 23:08:44,517 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-04 23:11:50,043 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 23:12:47,798 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 23:12:57,853 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 23:13:23,439 - INFO - register_de.py[:223] - AurelcHaywoodc024@nineboy.com.cn用户注册成功！
2019-07-04 23:13:28,540 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 23:13:32,803 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937C88>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b2a74c3a9c26ee28172b0bd3892a20bc
2019-07-04 23:13:33,815 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b2a74c3a9c26ee28172b0bd3892a20bc
2019-07-04 23:13:34,822 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077169374A8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/b2a74c3a9c26ee28172b0bd3892a20bc
2019-07-04 23:14:53,956 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 23:16:59,653 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 23:18:34,456 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 23:19:53,284 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 23:21:43,808 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 23:23:23,164 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 23:26:03,242 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 23:28:13,863 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 23:31:50,446 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 23:34:21,920 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 23:34:32,215 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 23:35:12,661 - INFO - register_de.py[:223] - LeigheLeetoc258@nineboy.top用户注册成功！
2019-07-04 23:35:14,432 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 23:35:18,592 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160BDDA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/18662d28603e172dd70725ca321144f2
2019-07-04 23:35:19,586 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C917B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/18662d28603e172dd70725ca321144f2
2019-07-04 23:35:20,589 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91668>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/18662d28603e172dd70725ca321144f2
2019-07-04 23:36:24,926 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-04 23:38:21,992 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 23:39:44,887 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 23:41:55,368 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 23:42:05,501 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 23:42:42,002 - INFO - register_de.py[:223] - BenedickaMitchellc102@nineboy.pro用户注册成功！
2019-07-04 23:42:46,264 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 23:42:49,403 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA19E8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1db867fe5f217c6d2f0a500bd701c98f
2019-07-04 23:42:50,410 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91EB8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1db867fe5f217c6d2f0a500bd701c98f
2019-07-04 23:42:51,442 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91D30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/1db867fe5f217c6d2f0a500bd701c98f
2019-07-04 23:45:14,460 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 23:46:29,179 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 23:47:24,806 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-04 23:47:35,466 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-04 23:48:02,238 - INFO - register_de.py[:223] - WaggoneraCorinc819@nineboy.site用户注册成功！
2019-07-04 23:48:07,969 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-04 23:48:12,273 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C790B8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0fcc6ef1b20978fbe9f5d66f2f16e1d4
2019-07-04 23:48:13,290 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C53860>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0fcc6ef1b20978fbe9f5d66f2f16e1d4
2019-07-04 23:48:14,290 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C53908>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/0fcc6ef1b20978fbe9f5d66f2f16e1d4
2019-07-04 23:50:19,541 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-04 23:51:13,413 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-04 23:52:46,297 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 23:54:05,993 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-04 23:55:22,595 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-04 23:57:07,098 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-05 00:02:17,528 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-05 00:04:05,543 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-05 00:06:46,145 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-05 00:08:22,874 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-05 00:10:43,447 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-05 00:14:27,616 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-05 00:15:48,025 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-05 00:16:36,150 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-05 00:16:46,186 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-05 00:17:05,140 - INFO - register_de.py[:223] - TrumancBrazila537@nineboy.vip用户注册成功！
2019-07-05 00:17:08,741 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-05 00:17:12,844 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C91470>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3291d813a68ae48907f62b744c1758dc
2019-07-05 00:17:13,845 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715C53940>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3291d813a68ae48907f62b744c1758dc
2019-07-05 00:17:14,847 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000077160AC2B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/3291d813a68ae48907f62b744c1758dc
2019-07-05 00:18:23,066 - INFO - register_de.py[:104] - 注册出错，程序结束！
2019-07-05 00:20:50,085 - INFO - register_de.py[:123] - 注册出错，程序结束！
2019-07-05 00:26:00,396 - INFO - register_de.py[:127] - 等待超时，程序终止！
2019-07-05 00:27:16,515 - INFO - register_de.py[:132] - 正在设置用户的基本信息...
2019-07-05 00:27:58,750 - INFO - register_de.py[:218] - 点击提交个人信息的设置!
2019-07-05 00:28:08,781 - INFO - register_de.py[:95] - 个人信息设置成功！success!
2019-07-05 00:28:25,816 - INFO - register_de.py[:223] - CarolcSimonea649@nineboy.biz用户注册成功！
2019-07-05 00:28:27,058 - INFO - register_de.py[:256] - 注册信息已成功入库！
2019-07-05 00:28:31,176 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007716937BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/38a8cdf9ce3016d8e265f244a7bb652f
2019-07-05 00:28:32,180 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1828>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/38a8cdf9ce3016d8e265f244a7bb652f
2019-07-05 00:28:33,179 - WARNING - connectionpool.py[:662] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000007715CA1748>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',)': /session/38a8cdf9ce3016d8e265f244a7bb652f
